/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eyBuild 1.1.2) automaticly,
 * build at: Sun Jul 27 17:49:50 2008
 */

#include <eblib.h>
#include "csp_p/_demo_main_csp.c"
#include "csp_p/_demo_test_csp.c"


#ifdef __cplusplus
extern "C" {
#endif

EB_CSP_MAPFILE csp_maplist[] = {
    {"/demo/main.csp", _demo_main_csp__, 0x1000, 0x10001000, NULL}, 
    {"/demo/test.csp", _demo_test_csp__, 0x1000, 0x10001001, NULL}, 
    {(char*)0, (CGI_PAGE_HOOK)0, 0, 0L, (unsigned char*)0}, 
};

#ifdef __cplusplus
}
#endif

