/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eyBuild 1.1.2) automaticly,
 * build at: Sun Jul 27 17:49:51 2008
 */

#include <eblib.h>

#ifdef __cplusplus
extern "C" {
#endif

extern EB_CSP_MAPFILE csp_maplist[3];

#ifdef __cplusplus
}
#endif

