/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eyBuild 1.1.2) automaticly,
 * build at: Sun Jul 27 17:49:51 2008
 */

#include <ebfrm.h>

#ifdef __cplusplus
extern "C" {
#endif

extern EB_ROM_MAPFILE rom_maplist[2];

#ifdef __cplusplus
}
#endif

