# 
# Copyright(C) eyBuild Group, 2005, 2006. All Rights Reserved.
#
# 01a, 2006-2-15  newzy create
#

.SILENT:

all:
	@echo make demo.cgi raw.cgi review.cgi test.cgi
	cd demo/unix;   $(MAKE) clean all
	cd raw/unix;    $(MAKE) clean all
	cd review/unix; $(MAKE) clean all
	cd test/unix;   $(MAKE) clean all
	cd cplus/unix;   $(MAKE) clean all

clean:
	@echo make clean ...
	cd demo/unix;   $(MAKE) clean
	cd raw/unix;    $(MAKE) clean
	cd review/unix; $(MAKE) clean
	cd test/unix;   $(MAKE) clean
	cd cplus/unix;   $(MAKE) clean



