/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_basic_status_csp.h"

/** GLOBAL **/

static int _basic_status_csp___mime_header(void * __ebfp);

int _basic_status_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "status.csp";
    char * __page_path = "/basic/";
    char * __page_fullname = "/basic/status.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    
    load_bbr(bbr, errmsg);

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_basic_status_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>Status</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript><!--\n"
        "function doRefresh()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"; return true;}\n"
        "function doConnect()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "&Connect=连 接\";return true;}\n"
        "function doDisConnect()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "&Disconnect=断 线\";return true;}\n"
        "function doRenew()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "&RenewIp=更新\";return true;}\n"
        "function doRelease()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "&ReleaseIp=释放\";return true;}\n"
        "function doLogin()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "&Login=登录\";return true;}\n"
        "function doLogout()\n"
        "{location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "&Logout=退出\";return true;}\n"
        "window.setTimeout(\"doRefresh()\",20000);\n"
        "--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post>\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "    width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>LAN口状态</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=420>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=80>MAC地址：</TD>\n"
        "                          <TD width=320>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->mac.lan_mac);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>IP 地址：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->lan.ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>子网掩码：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->lan.ipmask);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15 width=1><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 class=space width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "    width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>WAN口状态</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15 width=1><BR></TD>\n"
        "                  <TD height=50 width=500><TABLE align=center border=0 class=space width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=80>MAC地址：</TD>\n"
        "                          <TD width=140>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->mac.wan_mac);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD width=171>&nbsp;</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>IP 地址：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->wan.ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD>PPPoE</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>子网掩码：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->wan.ipmask);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD>&nbsp;</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>网关：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->wan.gateway);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>DNS服务器：</TD>\n"
        "                          <TD colSpan=2>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->dhcps.main_dsn_server);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        ", "
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->dhcps.backup_dsn_server);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>上网时间：</TD>\n"
        "                          0<TD>0 天 00:00:00</TD>\n"
        "                          <TD><DIV align=center>\n"
        "                              <INPUT class=button id=Disconnect name=Disconnect onclick=\"return doDisConnect();\" type=button value=\"断 线\">\n"
        "                            </DIV></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15 width=1><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 class=space width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "    width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>WAN口流量统计</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15 width=1><BR></TD>\n"
        "                  <TD height=50 width=500><TABLE align=center border=0 class=space width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=138>&nbsp;</TD>\n"
        "                          <TD width=138>接收</TD>\n"
        "                          <TD width=110>发送</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>字节数：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", 565973618);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", 753052564);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>数据包数：</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", 21928665);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", 11652569);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15 width=1><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "    <TABLE border=0 width=500>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD><TABLE align=center border=0 width=400>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD width=138>运行时间：</TD>\n"
        "                  <TD width=134>0 天 00:00:00</TD>\n"
        "                  <TD align=middle width=115><INPUT class=button id=Refresh name=Refresh onclick=\"return doRefresh();\" type=button value=\"刷 新\"></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        "\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _basic_status_csp__ */

static int _basic_status_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

