/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:11:31 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
                                      
/** GLOBAL **/

static int _basic_bottom_right_csp___mime_header(void * __ebfp);

int _basic_bottom_right_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "bottom_right.csp";
    char * __page_path = "/basic/";
    char * __page_fullname = "/basic/bottom_right.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_basic_bottom_right_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>bottom2</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "<META http-equiv=expires content=\"wed, 26 Feb 1997 08:21:57 GMT\">\n"
        "</HEAD>\n"
        "<BODY bottomMargin=0 leftMargin=0 rightMargin=0 topMargin=0>\n"
        "<TABLE border=0 cellPadding=0 cellSpacing=0 width=\"100%\">\n"
        "  <TBODY>\n"
        "    <TR>\n"
        "      <TD bgColor=#173a7e height=11 \n"
        "width=\"100%\"></TD>\n"
        "    </TR>\n"
        "  </TBODY>\n"
        "</TABLE>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _basic_bottom_right_csp__ */

static int _basic_bottom_right_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

