/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
                                
/** GLOBAL **/

static int _basic_banner_csp___mime_header(void * __ebfp);

int _basic_banner_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "banner.csp";
    char * __page_path = "/basic/";
    char * __page_fullname = "/basic/banner.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_basic_banner_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>banner</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<STYLE type=text/css>\n"
        ".font {\n"
        "	COLOR: #ffffff; FONT-FAMILY: \"Courier New\", \"Courier\", \"mono\"; FONT-SIZE: 12px\n"
        "}\n"
        "TD {\n"
        "	FONT-FAMILY: \"Times New Roman\", \"宋体\"; FONT-SIZE: 12px\n"
        "}\n"
        "FORM {\n"
        "	FONT-FAMILY: \"Times New Roman\", \"宋体\"; FONT-SIZE: 12px\n"
        "}\n"
        "BODY {\n"
        "	FONT-FAMILY: \"Arial Black\", \"黑体\"; FONT-SIZE: 16px\n"
        "}\n"
        ".unnamed1 {\n"
        "	LETTER-SPACING: 50px; WORD-SPACING: 100px\n"
        "}\n"
        ".unnamed2 {\n"
        "	WORD-SPACING: 100px\n"
        "}\n"
        ".style1 {\n"
        "	COLOR: #ffffff; FONT-FAMILY: \"黑体\"; FONT-SIZE: 36px; FONT-WEIGHT: bold; LETTER-SPACING: 5px; WORD-SPACING: 5px\n"
        "}\n"
        ".style2 {\n"
        "	FONT-FAMILY: Arial, Helvetica, sans-serif; FONT-SIZE: 32px; FONT-WEIGHT: bold\n"
        "}\n"
        "</STYLE>\n"
        "</HEAD>\n"
        "<BODY bottomMargin=0 leftMargin=0 rightMargin=0 topMargin=0>\n"
        "<TABLE border=0 cellPadding=0 cellSpacing=0 width=\"100%\">\n"
        "  <TBODY>\n"
        "    <TR>\n"
        "      <TD background="
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bg_title1.jpg width=72><IMG src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/banner.jpg\"></TD>\n"
        "      <TD \n"
        "      background="
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bg_title1.jpg>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<SPAN \n"
        "      class=style1>高性能宽带路由器</SPAN></TD>\n"
        "    </TR>\n"
        "    <TR>\n"
        "      <TD bgColor=#173a7e height=3 width=72></TD>\n"
        "      <TD bgColor=#173a7e height=3 width=\"100%\"></TD>\n"
        "    </TR>\n"
        "  </TBODY>\n"
        "</TABLE>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _basic_banner_csp__ */

static int _basic_banner_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

