/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_dhcp_fixmap_csp.h"

/** GLOBAL **/

static int _dhcp_fixmap_csp___mime_header(void * __ebfp);

int _dhcp_fixmap_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "fixmap.csp";
    char * __page_path = "/dhcp/";
    char * __page_fullname = "/dhcp/fixmap.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    int 				offset = 0;
    int 				ncurpage = 0;
    int 				max_count = 0;
    int 				i;
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    ncurpage = atoi(G("curpage"));
    offset = ncurpage * 8;
    max_count = MAX_DHCP_STATIC_HOST_NUM;
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    char 		mac[8];
    char 		ip[8];
    
    for (i=offset; i<offset+8; i++) {
    sprintf(mac, "mac%d", i);
    sprintf(ip, "ip%d", i);
    
    BUFCPY(bbr->static_dhcps[i].mac, G(mac));
    BUFCPY(bbr->static_dhcps[i].ip, G(ip));
    }
    
    save_bbr(bbr, errmsg);
    } else if (!isblankstr(G("PrevPage"))) {
    if (ncurpage > 0)
    offset = --ncurpage * 8;
    } else if (!isblankstr(G("NextPage"))) {
    if ((ncurpage+1)*8 < max_count)
    offset = ++ncurpage * 8;
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_dhcp_fixmap_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>staticaddr</TITLE>\n"
        "<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "<META http-equiv=expires content=\"wed, 26 Feb 1997 08:21:57 GMT\">\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" type=text/css rel=stylesheet>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function lastipverify(lastip,nMin,nMax){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"0123456789\";\n"
        "if(lastip.length = 0)\n"
        "return false;\n"
        "for (var i = 0; i < lastip.length; i++){\n"
        "c = lastip.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(lastip) < nMin || parseInt(lastip) > nMax)\n"
        "return false; return true;}\n"
        "function is_lastip(lastip_string,nMin,nMax){\n"
        "if(lastip_string.length == 0){\n"
        "alert(\"请输入IP地址（\" + nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "if (!lastipverify(lastip_string,nMin,nMax)){\n"
        "alert(\"IP地址输入错误，请重新输入（\"+ nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function macverify(mac_string){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"-0123456789ABCDEFabcdef\";\n"
        "if (mac_string.length != 17)\n"
        "return false;\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;\n"
        "else{\n"
        "if (c == \'-\')\n"
        "n++;}}\n"
        "if (n != 5)\n"
        "return false;\n"
        "for(var i = 2; i < 17; i += 3){\n"
        "if (mac_string.charAt(i) != \'-\')\n"
        "return false;\n"
        "}return true;}\n"
        "function is_macaddr(mac_string){\n"
        "if(mac_string.length == 0){\n"
        "alert(\"请输入MAC地址！\");\n"
        "return false;}\n"
        "if (!macverify(mac_string)){\n"
        "alert(\"MAC地址输入错误，请重新输入！\");\n"
        "return false;}return true;}\n"
        "function portverify(port_string){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "if(port_string.length == 0)\n"
        "return false;\n"
        "for (var i = 0; i < port_string.length; i++){\n"
        "c = port_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(port_string) <= 0 || parseInt(port_string) >= 65535)\n"
        "return false;return true;}\n"
        "function is_port(port_string){\n"
        "if(port_string.length == 0){\n"
        "alert(\"请输入端口地址（1－65534）！\");\n"
        "return false;}\n"
        "if (!portverify(port_string)){\n"
        "alert(\"端口地址输入错误，请重新输入（1－65534）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function is_number(num_string,nMin,nMax){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "for (var i = 0; i < num_string.length; i++){\n"
        "c = num_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if(parseInt(num_string) < nMin || parseInt(num_string) > nMax)\n"
        "return false;return true;}\n"
        "function is_domain(domain_string){\n"
        "var c;\n"
        "var ch = \"-.ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\";\n"
        "for (var i = 0; i < domain_string.length; i++){\n"
        "c = domain_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1){\n"
        "alert(\"输入中含有非法字符，请重新输入！\");\n"
        "return false;}}return true;}\n"
        "function is_spmac(mac_string){\n"
        "if(mac_string == \"00-00-00-00-00-00\"){\n"
        "alert(\"无效MAC地址，请重新输入！\");\n"
        "return false;}\n"
        "var ch = \"Ff-\";\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if(ch.indexOf(c) == -1)\n"
        "return true;}\n"
        "alert(\"无效MAC地址，请重新输入！\");\n"
        "return false;}\n"
        "function doSubmit(){\n"
        "var i = 0;\n"
        "for(i = 0; i < 16; i += 2){\n"
        "if(document.forms[0].elements[i+1].value != \"\"){\n"
        "if(!is_macaddr(document.forms[0].elements[i].value)){	\n"
        "var element =document.forms[0].elements[i];\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}\n"
        "if(!is_spmac(document.forms[0].elements[i].value)){\n"
        "var element =document.forms[0].elements[i];\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}}\n"
        "if(document.forms[0].elements[i].value != \"\"){\n"
        "if(!is_ipaddr(document.forms[0].elements[i+1].value)){\n"
        "var element =document.forms[0].elements[i+1];\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}}}\n"
        "var current,j;\n"
        "for(i = 0; i < 16; i += 2){	\n"
        "var current = document.forms[0].elements[i].value;\n"
        "for(j = i+2; j < 16; j += 2){\n"
        "if(current != \"\" && current == document.forms[0].elements[j].value){\n"
        "alert(\"不能有相同的MAC地址，请重新输入！\");\n"
        "var element = document.forms[0].elements[j];\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}}}\n"
        "for(i = 0; i < 16; i += 2){\n"
        "current = document.forms[0].elements[i+1].value;\n"
        "for(j = i+2; j < 16; j += 2){\n"
        "if(current != \"\" && current == document.forms[0].elements[j+1].value){\n"
        "alert(\"不能有相同的IP地址，请重新输入！\");\n"
        "var element = document.forms[0].elements[j+1];\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}}}\n"
        "alert(\"注意：只有在您重启路由器后，您所做的修改才能生效！\");\n"
        "return true;}\n"
        "function doPrev(){\n"
        "var ncurpage=document.forms[0].curpage.value;\n"
        "window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "PrevPage=255&curpage=\" + ncurpage;}\n"
        "function doNext(){\n"
        "var ncurpage=document.forms[0].curpage.value;\n"
        "window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "NextPage=255&curpage=\" + ncurpage;}\n"
        );
    goto_ERROR;

    #if 0
    #endif
    __ret=(int)ebBufStringAdd(__ebfp, 
        "function doClear(){\n"
        "for(var i = 0; i < 16; i += 2){\n"
        "document.forms[0].elements[i].value = \"\";\n"
        "document.forms[0].elements[i+1].value = \"\";}}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD class=title vAlign=center align=left width=495>静态地址分配</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE class=space cellSpacing=0 cellPadding=0 width=380 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页设置DHCP服务器的静态地址分配功能。通过此项功能，您可以更好地对局域网中的计算机进行管理和监控。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space width=420 align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=24>ID</TD>\n"
        "                          <TD align=middle width=215>MAC地址</TD>\n"
        "                          <TD align=middle width=139>IP地址</TD>\n"
        "                          <TD>&nbsp;</TD>\n"
        "                        </TR>\n"
        "					  "
        );
    goto_ERROR;

    for (i=offset; i<offset+8; i++) {
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                        <TR>\n"
        "                          <TD align=middle>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD align=middle><INPUT class=text id=mac"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " maxLength=17 \n"
        "                  size=18 name=mac"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->static_dhcps[i].mac);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                          <TD align=middle><INPUT class=text maxLength=15 size=15 name=ip"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "                            value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->static_dhcps[i].ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                          <TD align=middle>&nbsp;</TD>\n"
        "                        </TR>\n"
        "					  "
        );
    goto_ERROR;

    }
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\"/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=PrevPage "
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", offset<=0 ? "disabled": "");
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "  onclick=doPrev(); type=button value=上一页 name=PrevPage>\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=NextPage "
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", offset+8>=max_count-1 ? "disabled": "");
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " onclick=doNext(); type=button value=下一页 name=NextPage>\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=Clear onclick=doClear(); type=button value=\"清 空\" name=Clear>\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=Submit type=submit value=\"保 存\" name=Save>\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "    <INPUT type=hidden value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", ncurpage);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" name=curpage>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _dhcp_fixmap_csp__ */

static int _dhcp_fixmap_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

