/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
                        
/** GLOBAL **/

static int _main_csp___mime_header(void * __ebfp);

int _main_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "main.csp";
    char * __page_path = "/";
    char * __page_fullname = "/main.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_main_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>宽带路由器</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "</HEAD>\n"
        "<FRAMESET border=0 cols=* frameBorder=NO frameSpacing=0 rows=62,*,20>\n"
        "  <FRAMESET border=0 cols=133,* frameBorder=NO frameSpacing=0 rows=62>\n"
        "    <FRAME name=topLeftFrame noResize scrolling=no src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/basic/logo.csp\">\n"
        "    <FRAME name=topRightFrame noResize scrolling=no src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/basic/banner.csp\">\n"
        "  </FRAMESET>\n"
        "  <FRAMESET border=0 cols=145,* frameBorder=NO frameSpacing=0 rows=*>\n"
        "    <FRAME name=bottomLeftFrame noResize scrolling=no src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/menu.csp\">\n"
        "    <FRAME frameBorder=NO name=mainFrame src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/basic/status.csp\">\n"
        "  </FRAMESET>\n"
        );
    goto_ERROR;

    #if 1
    __ret=(int)ebBufStringAdd(__ebfp, 
        "    <FRAME noResize scrolling=no src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/basic/bottom.csp\">\n"
        );
    goto_ERROR;

    #else
    __ret=(int)ebBufStringAdd(__ebfp, 
        "  <FRAMESET border=0 cols=133,* frameBorder=NO frameSpacing=0 rows=11>\n"
        "    <FRAME src=\"UntitledFrame-5\" scrolling=no noResize rc=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/basic/bottom_left.csp\">\n"
        "  </FRAMESET>\n"
        );
    goto_ERROR;

    #endif
    __ret=(int)ebBufStringAdd(__ebfp, 
        "</FRAMESET>\n"
        "<noframes></noframes>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _main_csp__ */

static int _main_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

