/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_menu_csp.h"

/** GLOBAL **/

static int _menu_csp___mime_header(void * __ebfp);

int _menu_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "menu.csp";
    char * __page_path = "/";
    char * __page_fullname = "/menu.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_menu_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>menu</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<STYLE type=text/css>\n"
        "BODY {\n"
        "	BACKGROUND-COLOR: #f8c400; FONT-FAMILY: \"宋体\", \"Times New Roman\"; FONT-SIZE: 75px; MARGIN-LEFT: 15px; MARGIN-TOP: 15px; WHITE-SPACE: nowrap\n"
        "}\n"
        "TD.onelevel {\n"
        "	FONT-SIZE: 12px; HEIGHT: 18px; LINE-HEIGHT: 18px; PADDING-LEFT: 0px; TEXT-DECORATION: none\n"
        "}\n"
        "TD.onelevelsp {\n"
        "	FONT-SIZE: 12px; HEIGHT: 18px; LINE-HEIGHT: 18px; PADDING-LEFT: 0px; TEXT-DECORATION: none; WHITE-SPACE: nowrap\n"
        "}\n"
        "TD.twolevel {\n"
        "	FONT-SIZE: 12px; HEIGHT: 18px; LINE-HEIGHT: 18px; PADDING-LEFT: 0px; TEXT-DECORATION: none; WHITE-SPACE: nowrap\n"
        "}\n"
        "A.tp1:visited {\n"
        "	COLOR: #333333; FONT-FAMILY: \"宋体\", \"Times New Roman\"; TEXT-DECORATION: none; underline: none\n"
        "}\n"
        "A.tp1:hover {\n"
        "	COLOR: #ff0000; CURSOR: hand; FONT-FAMILY: \"宋体\", \"Times New Roman\"; TEXT-DECORATION: none\n"
        "}\n"
        "A.tp1:link {\n"
        "	COLOR: #333333; FONT-FAMILY: \"宋体\", \"Times New Roman\"; TEXT-DECORATION: none; underline: none\n"
        "}\n"
        "A.tp2:visited {\n"
        "	COLOR: #333333; FONT-FAMILY: \"宋体\", \"Times New Roman\"; TEXT-DECORATION: none; underline: none\n"
        "}\n"
        "A.tp2:hover {\n"
        "	COLOR: #ff0000; CURSOR: hand; FONT-FAMILY: \"宋体\", \"Times New Roman\"; TEXT-DECORATION: none\n"
        "}\n"
        "A.tp2:link {\n"
        "	COLOR: #333333; FONT-FAMILY: \"宋体\", \"Times New Roman\"; TEXT-DECORATION: none; underline: none\n"
        "}\n"
        "</STYLE>\n"
        "<SCRIPT language=javascript><!--\n"
        "function Click() { \n"
        "    window.event.returnValue = true;\n"
        "}\n"
        "function ResetStatus(strInfo) {\n"
        "    window.status=\"\"; \n"
        "    return true;\n"
        "}\n"
        "\n"
        "document.oncontextmenu=Click;\n"
        "	\n"
        "function OnHrefClick(mainID,subID) {	//主菜单和子菜单index\n"
        "	if(mainID==null)  mainID=\'A\';\n"
        "	if(subID==null)  subID=0;\n"
        "	var MenuHtml =\'"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/menu.csp\' + \n"
        "	    \'&MainID=\' + mainID + \'&SubID=\' + subID;\n"
        "	window.location.href =MenuHtml;\n"
        "	return false;  \n"
        "}\n"
        "\n"
        "var MainFrameHtml  =\'"
        );
    goto_ERROR;

    menu_get_page(__ebfp, getParameter("MainID"), getParameter("SubID"));
    __ret=(int)ebBufStringAdd(__ebfp, 
        "\';\n"
        "if (null != parent && parent.mainFrame)\n"
        "    parent.mainFrame.location.href=MainFrameHtml;\n"
        "--></SCRIPT>\n"
        "<META content=\"MSHTML 5.00.3700.6699\" name=GENERATOR>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<TABLE border=0 width=124>\n"
        "  <TBODY>\n"
        "    "
        );
    goto_ERROR;

    menu_update(__ebfp, getParameter("MainID"), getParameter("SubID"));
    __ret=(int)ebBufStringAdd(__ebfp, 
        "  </TBODY>\n"
        "</TABLE>\n"
        "</BODY>\n"
        "</HTML>\n"
        "\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _menu_csp__ */

static int _menu_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

