/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
                            
/** GLOBAL **/

static int _nat_upnp_csp___mime_header(void * __ebfp);

int _nat_upnp_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "upnp.csp";
    char * __page_path = "/nat/";
    char * __page_fullname = "/nat/upnp.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_nat_upnp_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>UPnP</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function lastipverify(lastip,nMin,nMax){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"0123456789\";\n"
        "if(lastip.length = 0)\n"
        "return false;\n"
        "for (var i = 0; i < lastip.length; i++){\n"
        "c = lastip.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(lastip) < nMin || parseInt(lastip) > nMax)\n"
        "return false; return true;}\n"
        "function is_lastip(lastip_string,nMin,nMax){\n"
        "if(lastip_string.length == 0){\n"
        "alert(\"请输入IP地址（\" + nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "if (!lastipverify(lastip_string,nMin,nMax)){\n"
        "alert(\"IP地址输入错误，请重新输入（\"+ nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function macverify(mac_string){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"-0123456789ABCDEFabcdef\";\n"
        "if (mac_string.length != 17)\n"
        "return false;\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;\n"
        "else{\n"
        "if (c == \'-\')\n"
        "n++;}}\n"
        "if (n != 5)\n"
        "return false;\n"
        "for(var i = 2; i < 17; i += 3){\n"
        "if (mac_string.charAt(i) != \'-\')\n"
        "return false;\n"
        "}return true;}\n"
        "function is_macaddr(mac_string){\n"
        "if(mac_string.length == 0){\n"
        "alert(\"请输入MAC地址！\");\n"
        "return false;}\n"
        "if (!macverify(mac_string)){\n"
        "alert(\"MAC地址输入错误，请重新输入！\");\n"
        "return false;}return true;}\n"
        "function portverify(port_string){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "if(port_string.length == 0)\n"
        "return false;\n"
        "for (var i = 0; i < port_string.length; i++){\n"
        "c = port_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(port_string) <= 0 || parseInt(port_string) >= 65535)\n"
        "return false;return true;}\n"
        "function is_port(port_string){\n"
        "if(port_string.length == 0){\n"
        "alert(\"请输入端口地址（1－65534）！\");\n"
        "return false;}\n"
        "if (!portverify(port_string)){\n"
        "alert(\"端口地址输入错误，请重新输入（1－65534）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function is_number(num_string,nMin,nMax){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "for (var i = 0; i < num_string.length; i++){\n"
        "c = num_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if(parseInt(num_string) < nMin || parseInt(num_string) > nMax)\n"
        "return false;return true;}\n"
        "function is_domain(domain_string){\n"
        "var c;\n"
        "var ch = \"-.ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\";\n"
        "for (var i = 0; i < domain_string.length; i++){\n"
        "c = domain_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1){\n"
        "alert(\"输入中含有非法字符，请重新输入！\");\n"
        "return false;}}return true;}\n"
        "function doHelp(){alert(\"请输入正确的帮助信息！\");}\n"
        "function doRefresh() {location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"}\n"
        "var maxEntry = 0;\n"
        "var delParas = new Array(0);\n"
        "for (n = 0; n < delParas.length; n ++)\n"
        "delParas[n] = 0;\n"
        "function changeDelPara(para){ if ((para < 0) || (para >= maxEntry)) return;delParas[(para >> 5)] ^= 1 << (para & (32 - 1)); //alert(\'delParas[\'+(para >> 5)+\'] = \'+delParas[(para >> 5)]);\n"
        "}\n"
        "function doUPnPDel(){var paras = \'\';\n"
        " for (n = delParas.length; 0 != n; n --)\n"
        "paras+=delParas[n - 1]+\',\';//alert(paras);\n"
        "location.href=\"/userRpm/UpnpCfgRpm.htm\?DelUPnP=\"+paras}\n"
        "function doUPnPClearAll(){\n"
        "if(confirm(\"确认要删除所有UPnP条目\? \")){for (n = 0; n < maxEntry; n ++)\n"
        "delParas[(n >> 5)] |= 1 << (n & (32 - 1));\n"
        "doUPnPDel();\n"
        "}}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post>\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=560>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=553>UPnP设置</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=560>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=558><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=514>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页设置/显示UPnP的设置以及工作状态。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=514>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>当前UPnP状态：<B>已关闭</B>&nbsp;&nbsp;\n"
        "                            <INPUT class=button name=ENUPnP disabled type=submit value=启用UPnP></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <DIV align=center><BR align=\"center\">\n"
        "                      当前UPnP设置列表\n"
        "                      <TABLE align=center border=1 cellPadding=0 cellSpacing=0 \n"
        "              width=514>\n"
        "                        <TBODY>\n"
        "                          <TR>\n"
        "                            <TD align=middle>ID</TD>\n"
        "                            <TD align=middle>应用描述</TD>\n"
        "                            <TD align=middle>外部端口</TD>\n"
        "                            <TD align=middle>协议类型</TD>\n"
        "                            <TD align=middle>内部端口</TD>\n"
        "                            <TD align=middle>IP地址</TD>\n"
        "                            <TD align=middle>状态</TD>\n"
        "                            <TD align=middle>删除</TD>\n"
        "                          </TR>\n"
        "                        </TBODY>\n"
        "                      </TABLE>\n"
        "                      <P></P>\n"
        "                    </DIV></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "        width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button name=Refresh onclick=\"return doRefresh();\" type=button value=\"刷 新\">\n"
        "&nbsp;\n"
        "                    <INPUT class=button name=dele onclick=doUPnPDel(); disabled type=button value=\"删 除\">\n"
        "&nbsp;\n"
        "                    <INPUT class=button name=deleAll onclick=doUPnPClearAll(); disabled type=button value=删除所有>\n"
        "                  </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "        width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _nat_upnp_csp__ */

static int _nat_upnp_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

