/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_nat_dmz_csp.h"

/** GLOBAL **/

static int _nat_dmz_csp___mime_header(void * __ebfp);

int _nat_dmz_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "dmz.csp";
    char * __page_path = "/nat/";
    char * __page_fullname = "/nat/dmz.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    BUFCPY(bbr->dmz.ip, G("ipb"));
    bbr->dmz.enable = atoi(G("enable"));
    
    save_bbr(bbr, errmsg);
    }
    

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_nat_dmz_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>DMZ</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function lastipverify(lastip,nMin,nMax){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"0123456789\";\n"
        "if(lastip.length = 0)\n"
        "return false;\n"
        "for (var i = 0; i < lastip.length; i++){\n"
        "c = lastip.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(lastip) < nMin || parseInt(lastip) > nMax)\n"
        "return false; return true;}\n"
        "function is_lastip(lastip_string,nMin,nMax){\n"
        "if(lastip_string.length == 0){\n"
        "alert(\"请输入IP地址（\" + nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "if (!lastipverify(lastip_string,nMin,nMax)){\n"
        "alert(\"IP地址输入错误，请重新输入（\"+ nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function macverify(mac_string){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"-0123456789ABCDEFabcdef\";\n"
        "if (mac_string.length != 17)\n"
        "return false;\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;\n"
        "else{\n"
        "if (c == \'-\')\n"
        "n++;}}\n"
        "if (n != 5)\n"
        "return false;\n"
        "for(var i = 2; i < 17; i += 3){\n"
        "if (mac_string.charAt(i) != \'-\')\n"
        "return false;\n"
        "}return true;}\n"
        "function is_macaddr(mac_string){\n"
        "if(mac_string.length == 0){\n"
        "alert(\"请输入MAC地址！\");\n"
        "return false;}\n"
        "if (!macverify(mac_string)){\n"
        "alert(\"MAC地址输入错误，请重新输入！\");\n"
        "return false;}return true;}\n"
        "function portverify(port_string){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "if(port_string.length == 0)\n"
        "return false;\n"
        "for (var i = 0; i < port_string.length; i++){\n"
        "c = port_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(port_string) <= 0 || parseInt(port_string) >= 65535)\n"
        "return false;return true;}\n"
        "function is_port(port_string){\n"
        "if(port_string.length == 0){\n"
        "alert(\"请输入端口地址（1－65534）！\");\n"
        "return false;}\n"
        "if (!portverify(port_string)){\n"
        "alert(\"端口地址输入错误，请重新输入（1－65534）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function is_number(num_string,nMin,nMax){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "for (var i = 0; i < num_string.length; i++){\n"
        "c = num_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if(parseInt(num_string) < nMin || parseInt(num_string) > nMax)\n"
        "return false;return true;}\n"
        "function is_domain(domain_string){\n"
        "var c;\n"
        "var ch = \"-.ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\";\n"
        "for (var i = 0; i < domain_string.length; i++){\n"
        "c = domain_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1){\n"
        "alert(\"输入中含有非法字符，请重新输入！\");\n"
        "return false;}}return true;}\n"
        "var   ele_num = 2;\n"
        "function doSubmit()\n"
        "{\n"
        "if(ele_num==3)\n"
        "{\n"
        "if(document.forms[0].elements[0].value!=\"\"||\n"
        "document.forms[0].elements[1].value!=\"\")\n"
        "{	if((document.forms[0].elements[0].value==0&&document.forms[0].elements[1].value==0)||\n"
        "document.forms[0].elements[0].value<0||\n"
        "document.forms[0].elements[0].value>255||\n"
        "document.forms[0].elements[1].value<0||\n"
        "document.forms[0].elements[1].value>255||\n"
        "		(document.forms[0].elements[0].value==255&&document.forms[0].elements[1].value==255))\n"
        "	{	alert(\"IP地址输入错误，请重新输入！\");\n"
        "		return false;}\n"
        "}}\n"
        "else\n"
        "{\n"
        "if(document.forms[0].elements[0].value!=\"\")\n"
        "{	if(!is_number(document.forms[0].elements[0].value, 1, 255) || \n"
        "document.forms[0].elements[0].value==0||\n"
        "document.forms[0].elements[0].value<=0||\n"
        "document.forms[0].elements[0].value>=255||\n"
        "document.forms[0].elements[0].value==255)\n"
        "	{	alert(\"IP地址输入错误，请重新输入(1-254)！\");\n"
        "		return false;	}\n"
        "}}\n"
        "	return true;\n"
        "}\n"
        "\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>DMZ主机</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>在正常情况下，NAT路由器是禁止广域网直接访问局域网里的计算机的。但是，有些时候我们又需要将局域网内的某台计算机开放给广域网，以实现双向通信，此时只要把该计算机设置为DMZ主机就可以实现了。</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>( 注意:设置DMZ主机之后，与该IP相关的防火墙设置将不起作用。)</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=100>DMZ主机IP地址:</TD>\n"
        "                          <TD width=150>192.168.1.\n"
        "                            <INPUT class=text id=ipb maxLength=3 name=ipb size=3\n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->dmz.ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            </TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    CHECK_BOX2("enable", "1", bbr->dmz.enable, "");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "&nbsp;启用</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "        width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=Submit name=Save type=submit value=\"保 存\">\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "        width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _nat_dmz_csp__ */

static int _nat_dmz_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

