/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_nat_special_app_csp.h"

/** GLOBAL **/

static int _nat_special_app_csp___mime_header(void * __ebfp);

int _nat_special_app_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "special_app.csp";
    char * __page_path = "/nat/";
    char * __page_fullname = "/nat/special_app.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    char				protocol[16];
    char  				enable[16];
    int 				i;
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    char 		pt[16]  = "";
    char 		opt[16] = "";
    
    for (i=0; i<MAX_SPECIAL_APP_NUM; i++) {
    sprintf(pt, "pt%d", i);
    sprintf(protocol, "pr%d", i);
    sprintf(opt, "oPt%d", i);
    sprintf(enable, "enable%d", i);
    
    bbr->special_app[i].trigger_port = atoi(G(pt));
    BUFCPY(bbr->special_app[i].trigger_protocol, G(protocol));
    BUFCPY(bbr->special_app[i].port_list, G(opt));
    sprintf(protocol, "oPr%d", i);
    BUFCPY(bbr->special_app[i].protocol, G(protocol));
    bbr->special_app[i].enable = atoi(G(enable));
    }
    
    save_bbr(bbr, errmsg);
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_nat_special_app_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>spprogram</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function lastipverify(lastip,nMin,nMax){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"0123456789\";\n"
        "if(lastip.length = 0)\n"
        "return false;\n"
        "for (var i = 0; i < lastip.length; i++){\n"
        "c = lastip.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(lastip) < nMin || parseInt(lastip) > nMax)\n"
        "return false; return true;}\n"
        "function is_lastip(lastip_string,nMin,nMax){\n"
        "if(lastip_string.length == 0){\n"
        "alert(\"请输入IP地址（\" + nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "if (!lastipverify(lastip_string,nMin,nMax)){\n"
        "alert(\"IP地址输入错误，请重新输入（\"+ nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function macverify(mac_string){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"-0123456789ABCDEFabcdef\";\n"
        "if (mac_string.length != 17)\n"
        "return false;\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;\n"
        "else{\n"
        "if (c == \'-\')\n"
        "n++;}}\n"
        "if (n != 5)\n"
        "return false;\n"
        "for(var i = 2; i < 17; i += 3){\n"
        "if (mac_string.charAt(i) != \'-\')\n"
        "return false;\n"
        "}return true;}\n"
        "function is_macaddr(mac_string){\n"
        "if(mac_string.length == 0){\n"
        "alert(\"请输入MAC地址！\");\n"
        "return false;}\n"
        "if (!macverify(mac_string)){\n"
        "alert(\"MAC地址输入错误，请重新输入！\");\n"
        "return false;}return true;}\n"
        "function portverify(port_string){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "if(port_string.length == 0)\n"
        "return false;\n"
        "for (var i = 0; i < port_string.length; i++){\n"
        "c = port_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(port_string) <= 0 || parseInt(port_string) >= 65535)\n"
        "return false;return true;}\n"
        "function is_port(port_string){\n"
        "if(port_string.length == 0){\n"
        "alert(\"请输入端口地址（1－65534）！\");\n"
        "return false;}\n"
        "if (!portverify(port_string)){\n"
        "alert(\"端口地址输入错误，请重新输入（1－65534）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function is_number(num_string,nMin,nMax){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "for (var i = 0; i < num_string.length; i++){\n"
        "c = num_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if(parseInt(num_string) < nMin || parseInt(num_string) > nMax)\n"
        "return false;return true;}\n"
        "function is_domain(domain_string){\n"
        "var c;\n"
        "var ch = \"-.ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\";\n"
        "for (var i = 0; i < domain_string.length; i++){\n"
        "c = domain_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1){\n"
        "alert(\"输入中含有非法字符，请重新输入！\");\n"
        "return false;}}return true;}\n"
        "function is_port(ch,port_string){\n"
        "var c;\n"
        "for (var i = 0; i < port_string.length; i++){\n"
        "c = port_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}return true;}\n"
        "function doSubmit(){\n"
        "for(i=0;i<8;i++)\n"
        "{var element;\n"
        "var cnt, ptstr, c;\n"
        "element=document.forms[0].elements[i*5+2]; ptstr=element.value; cnt=0\n"
        "for(var j=0;j<ptstr.length;j++){\n"
        "if (ptstr.charAt(j)==\',\') cnt++;}\n"
        "if (cnt>4){element.focus();element.select();alert(\"只能输入5个开放端口号段！\");return false;}\n"
        "if(document.forms[0].elements[i*5+4].checked==true)\n"
        "{element=document.forms[0].elements[i*5];\n"
        "if(element.value==\"\")\n"
        "{element.focus();element.select();alert(\"请输入触发端口号！\");return false;}\n"
        "element=document.forms[0].elements[i*5+2];\n"
        "if(element.value==\"\")\n"
        "{element.focus();element.select();alert(\"请输入开放端口号！\");return false;}}}\n"
        "var ch1 = \"0123456789\";\n"
        "var ch2 = \"-,0123456789\";\n"
        "for(var i = 0; i < 40; i += 5){\n"
        "if(!is_port(ch1,document.forms[0].elements[i].value)){\n"
        "alert(\"端口输入中含有非法字符，请重新输入！\");\n"
        "var element = document.forms[0].elements[i];\n"
        "if(element){element.focus();element.select();}return false;}\n"
        "if(!is_port(ch2,document.forms[0].elements[i+2].value)){\n"
        "alert(\"端口输入中含有非法字符，请重新输入！\");\n"
        "var element = document.forms[0].elements[i+2];\n"
        "if(element){element.focus();\n"
        "element.select();}return false;}}\n"
        "return true;}\n"
        "function doClear(){\n"
        "for(var i = 0; i < 40; i += 5){\n"
        "document.forms[0].elements[i].value = \"\";\n"
        "document.forms[0].elements[i+1].selectedIndex = 0;\n"
        "document.forms[0].elements[i+2].value = \"\";\n"
        "document.forms[0].elements[i+3].selectedIndex = 0;\n"
        "document.forms[0].elements[i+4].checked = false;}}\n"
        "function planet(iPort,oPort){this.iPort=iPort;this.oPort=oPort;}\n"
        "function doLoad(){lis = new Array(9);\n"
        "lis[0] = new planet(\"6112\",\"6112\");\n"
        "lis[1] = new planet(\"7175\",\"51200-51201,51210\");\n"
        "lis[2] = new planet(\"2019\",\"2000-2038,2050-2051,2069,2085,3010-3030\");\n"
        "lis[3] = new planet(\"47624\",\"2300-2400,28800-29000\");\n"
        "lis[4] = new planet(\"12053\",\"12120,12122,24150-24220\");\n"
        "lis[5] = new planet(\"554\",\"6970-6999\");\n"
        "lis[6] = new planet(\"47624\",\"2300-2400,28800-29000\");\n"
        "lis[7] = new planet(\"47624\",\"2300-2400\");\n"
        "lis[8] = new planet(\"47624\",\"2300-2400\");}\n"
        "function doFill(){\n"
        "var destIndex;var srcIndex;\n"
        "srcIndex=document.forms[0].app.selectedIndex;\n"
        "if(srcIndex==0) return;\n"
        "destIndex=document.forms[0].ids.value;\n"
        "document.forms[0].elements[5*destIndex].value=lis[srcIndex-1].iPort;\n"
        "document.forms[0].elements[5*destIndex+2].value=lis[srcIndex-1].oPort;\n"
        "document.forms[0].elements[5*destIndex+4].checked=true;}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY onload=doLoad();>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>特殊应用程序</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=480>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>某些特殊的应用，比如视频会议，Internet游戏，网络电话等，可能无法在简单的NAT路由器下正常工作。但是，通过本页的正确设置之后，就可以弥补以上的这些缺憾，使得这些应用能够正常工作。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 class=space width=480>\n"
        "                      <TBODY>\n"
        "                        <TR align=middle>\n"
        "                          <TD>ID</TD>\n"
        "                          <TD>触发端口</TD>\n"
        "                          <TD>触发协议</TD>\n"
        "                          <TD>开放端口</TD>\n"
        "                          <TD>开放协议</TD>\n"
        "                          <TD>启用</TD>\n"
        "                        </TR>\n"
        "					  "
        );
    goto_ERROR;

    for (i=0; i<MAX_SPECIAL_APP_NUM; i++) {
    sprintf(protocol, "pr%d", i);
    sprintf(enable, "enable%d", i);
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                        <TR align=middle>\n"
        "                          <TD>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                          <TD><INPUT class=text maxLength=5 name=pt"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=6\n"
        "                              value=\""
        );
    goto_ERROR;

    bbr->special_app[i].trigger_port ? print("%d", bbr->special_app[i].trigger_port) : 0;
    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                          </TD>\n"
        "                          <TD>\n"
        "                          "
        );
    goto_ERROR;

    SELECT_BEGIN(protocol, bbr->special_app[i].trigger_protocol, "class=list")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("1", "ALL")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("2", "TCP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("3", "UDP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "						  </TD>\n"
        "                          <TD><INPUT class=text maxLength=59 name=oPt"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=40\n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->special_app[i].port_list);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                          </TD>\n"
        "                          <TD>\n"
        "                          "
        );
    goto_ERROR;

    sprintf(protocol, "oPr%d", i);
    SELECT_BEGIN(protocol, bbr->special_app[i].protocol, "class=list")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("1", "ALL")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("2", "TCP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("3", "UDP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "						  </TD>\n"
        "                          <TD>"
        );
    goto_ERROR;

    CHECK_BOX2(enable, "1", bbr->special_app[i].enable, "");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "</TD>\n"
        "                        </TR>\n"
        " 					 "
        );
    goto_ERROR;

    }
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                     </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 class=space width=480>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=112>常用应用程序：</TD>\n"
        "                          <TD noWrap width=117>\n"
        "                          "
        );
    goto_ERROR;

    SELECT_BEGIN("app", "", "class=list")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("0", "- - - 选项 - - -")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("1", "Battle.net")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("2", "Dialpad")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("3", "ICU II")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("4", "MSN Gaming Zone")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("5", "PC-to-Phone")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("6", "Quick Time 4")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("7", "AOE II Client")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("8", "Sudden Strike")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("9", "Baldurs Gate II")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "						  </TD>\n"
        "                          <TD noWrap width=82><INPUT class=button name=fill onclick=doFill(); type=button value=填空到>\n"
        "&nbsp;ID</TD>\n"
        "                          <TD noWrap width=108>\n"
        "                          <SELECT class=list name=ids>\n"
        "                              <OPTION selected value=0>1</OPTION>\n"
        "                              <OPTION value=1>2</OPTION>\n"
        "                              <OPTION value=2>3</OPTION>\n"
        "                              <OPTION value=3>4</OPTION>\n"
        "                              <OPTION value=4>5</OPTION>\n"
        "                              <OPTION value=5>6</OPTION>\n"
        "                              <OPTION value=6>7</OPTION>\n"
        "                              <OPTION value=7>8</OPTION>\n"
        "                            </SELECT></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button name=Save type=submit value=\"保 存\">\n"
        "&nbsp;\n"
        "                    <INPUT class=button name=clear onclick=doClear(); type=button value=\"清 空\">\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _nat_special_app_csp__ */

static int _nat_special_app_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

