/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_nat_virtualserver_csp.h"

/** GLOBAL **/

static int _nat_virtualserver_csp___mime_header(void * __ebfp);

int _nat_virtualserver_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "virtualserver.csp";
    char * __page_path = "/nat/";
    char * __page_fullname = "/nat/virtualserver.csp";
/** DECLARE **/
    char		gport[16];
    char		gid[16], num[16];

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    char				protocol[16];
    char  				enable[16];
    int 				offset = 0;
    int 				ncurpage = 0;
    int 				max_count = 0;
    int 				i;
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    ncurpage = atoi(G("curpage"));
    offset = ncurpage * 8;
    max_count = MAX_VIRTUAL_HOST_NUM;
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    char 		port[16];
    char 		ipb[16];
    
    for (i=offset; i<offset+8; i++) {
    sprintf(port, "port%d", i);
    sprintf(ipb, "ipb%d", i);
    sprintf(protocol, "protocol%d", i);
    sprintf(enable, "enable%d", i);
    
    BUFCPY(bbr->virtual_host[i].server_port, G(port));
    BUFCPY(bbr->virtual_host[i].server_ip, G(ipb));
    BUFCPY(bbr->virtual_host[i].protocol, G(protocol));
    bbr->virtual_host[i].enable = atoi(G(enable));
    }
    
    bbr->virtual_host[i].general_port = atoi(G("ports"));
    bbr->virtual_host[i].id = atoi(G("ids"));
    
    save_bbr(bbr, errmsg);
    } else if (!isblankstr(G("PrevPage"))) {
    if (ncurpage > 0)
    offset = --ncurpage * 8;
    } else if (!isblankstr(G("NextPage"))) {
    if ((ncurpage+1)*8 < max_count)
    offset = ++ncurpage * 8;
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_nat_virtualserver_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>Virtual Server</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function lastipverify(lastip,nMin,nMax){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"0123456789\";\n"
        "if(lastip.length = 0)\n"
        "return false;\n"
        "for (var i = 0; i < lastip.length; i++){\n"
        "c = lastip.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(lastip) < nMin || parseInt(lastip) > nMax)\n"
        "return false; return true;}\n"
        "function is_lastip(lastip_string,nMin,nMax){\n"
        "if(lastip_string.length == 0){\n"
        "alert(\"请输入IP地址（\" + nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "if (!lastipverify(lastip_string,nMin,nMax)){\n"
        "alert(\"IP地址输入错误，请重新输入（\"+ nMin + \"－\" + nMax + \"）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function macverify(mac_string){\n"
        "var c;\n"
        "var n = 0;\n"
        "var ch = \"-0123456789ABCDEFabcdef\";\n"
        "if (mac_string.length != 17)\n"
        "return false;\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;\n"
        "else{\n"
        "if (c == \'-\')\n"
        "n++;}}\n"
        "if (n != 5)\n"
        "return false;\n"
        "for(var i = 2; i < 17; i += 3){\n"
        "if (mac_string.charAt(i) != \'-\')\n"
        "return false;\n"
        "}return true;}\n"
        "function is_macaddr(mac_string){\n"
        "if(mac_string.length == 0){\n"
        "alert(\"请输入MAC地址！\");\n"
        "return false;}\n"
        "if (!macverify(mac_string)){\n"
        "alert(\"MAC地址输入错误，请重新输入！\");\n"
        "return false;}return true;}\n"
        "function portverify(port_string){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "if(port_string.length == 0)\n"
        "return false;\n"
        "for (var i = 0; i < port_string.length; i++){\n"
        "c = port_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if (parseInt(port_string) <= 0 || parseInt(port_string) >= 65535)\n"
        "return false;return true;}\n"
        "function is_port(port_string){\n"
        "if(port_string.length == 0){\n"
        "alert(\"请输入端口地址（1－65534）！\");\n"
        "return false;}\n"
        "if (!portverify(port_string)){\n"
        "alert(\"端口地址输入错误，请重新输入（1－65534）！\");\n"
        "return false;}\n"
        "return true;}\n"
        "function is_number(num_string,nMin,nMax){\n"
        "var c;\n"
        "var ch = \"0123456789\";\n"
        "for (var i = 0; i < num_string.length; i++){\n"
        "c = num_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1)\n"
        "return false;}\n"
        "if(parseInt(num_string) < nMin || parseInt(num_string) > nMax)\n"
        "return false;return true;}\n"
        "function is_domain(domain_string){\n"
        "var c;\n"
        "var ch = \"-.ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\";\n"
        "for (var i = 0; i < domain_string.length; i++){\n"
        "c = domain_string.charAt(i);\n"
        "if (ch.indexOf(c) == -1){\n"
        "alert(\"输入中含有非法字符，请重新输入！\");\n"
        "return false;}}return true;}\n"
        "function is_portcharacter(port_string){\n"
        "	var c;\n"
        "	var ch = \"-0123456789\";\n"
        "	for (var i = 0; i < port_string.length; i++)\n"
        "	{\n"
        "		c = port_string.charAt(i);\n"
        "		if (ch.indexOf(c) == -1)\n"
        "			return false;\n"
        "	}\n"
        "	return true;\n"
        "}\n"
        "function doPrev(){\n"
        "var ncurpage=document.forms[0].curpage.value;\n"
        "window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "PrevPage=255&curpage=\" + ncurpage;}\n"
        "function doNext(){\n"
        "var ncurpage=document.forms[0].curpage.value;\n"
        "window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "NextPage=255&curpage=\" + ncurpage;}\n"
        "var  ele_num = 4;\n"
        "var  rec_num = 8;\n"
        "function doClear()\n"
        "{\n"
        "	for(var i = 0; i<rec_num; i++)\n"
        "	{\n"
        "		for(var j=0; j<ele_num-2;j++)\n"
        "			document.forms[0].elements[i*ele_num+j].value =\"\"; \n"
        "		document.forms[0].elements[i*ele_num+j].selectedIndex = 0;	\n"
        "		document.forms[0].elements[i*ele_num+j+1].checked = false;\n"
        "	}\n"
        "}\n"
        "function doFill()\n"
        "{\n"
        "	var n = document.forms[0].ports.selectedIndex;\n"
        "	var m = document.forms[0].ids.selectedIndex;\n"
        "	var v = document.forms[0].ports.options[n].text;\n"
        "	var ALL=0, TCP=1, UDP=2;\n"
        "	//				 DNS, FTP, GOPHER, HTTP, NNTP, POP3, PPTP, SMTP, SOCK, TELNET\n"
        "	Pro = new Array( ALL ,TCP  ,TCP,   TCP , TCP , TCP,   ALL,  TCP,  ALL,  TCP);\n"
        "	var t1 = v.indexOf(\"(\");\n"
        "	var t2 = v.lastIndexOf(\")\");\n"
        "	if((n >= 0) && (m >= 0) && (t1 >= 0) && (t2 >= 0))\n"
        "	{\n"
        "		document.forms[0].elements[m*ele_num].value = v.substring(t1+1,t2);\n"
        "		document.forms[0].elements[m*ele_num+ele_num-2].selectedIndex = Pro[n];\n"
        "		\n"
        "	}\n"
        "}\n"
        "function ValueValidate( value, nIndex, nMin, nMax)\n"
        "{\n"
        "	if(nIndex==0)\n"
        "	{\n"
        "		if(value.length==0 || parseInt(value)==0)\n"
        "		{	\n"
        "			alert(\"端口号不能为空或为零!\");\n"
        "			return false;\n"
        "		}\n"
        "		else if(!is_portcharacter(value))\n"
        "		{\n"
        "			alert(\"端口号含有非法字符，请重新输入！\");\n"
        "			return false;\n"
        "		}\n"
        "		else	\n"
        "			return true;\n"
        "	}\n"
        "	else\n"
        "		return is_lastip(value, nMin ,nMax);\n"
        "}\n"
        "function doSubmit()\n"
        "{\n"
        "	var ELE_MAX = ele_num -2;\n"
        "	var i , j, k;\n"
        "	for(i = 0; i < rec_num; i++)\n"
        "	{\n"
        "		for(j=0;j<ELE_MAX;j++)\n"
        "		{\n"
        "			nAllNull= true; \n"
        "			nIsOk	= true;\n"
        "			MINIP	= 1; MAXIP	= 254;\n"
        "			if(ele_num>4)\n"
        "			{\n"
        "				MINIP	= 0; MAXIP	= 255;\n"
        "			}\n"
        "			ele = document.forms[0].elements[i*ele_num+j];\n"
        "			if(ele.value !=\"\")\n"
        "			{\n"
        "\n"
        "				nIsOk = ValueValidate(ele.value, j, MINIP, MAXIP );\n"
        "				if(nIsOk==true&&ele_num>4&&j==1)\n"
        "				{\n"
        "					if((document.forms[0].elements[i*ele_num+j].value==0&&\n"
        "						document.forms[0].elements[i*ele_num+j+1].value==0)||\n"
        "						(document.forms[0].elements[i*ele_num+j].value==255&&\n"
        "						document.forms[0].elements[i*ele_num+j+1].value==255))\n"
        "					{\n"
        "						alert(\"IP地址错误！请重新输入！\");\n"
        "						nIsOk = false;\n"
        "					}\n"
        "				}\n"
        "			}\n"
        "\n"
        "			else\n"
        "			{\n"
        "				for( k=0;k< ELE_MAX ;k++)\n"
        "				{\n"
        "					if(k==j)\n"
        "						continue;\n"
        "					ele_temp =document.forms[0].elements[i*ele_num+k];\n"
        "					if(ele_temp.value !=\"\")\n"
        "					{\n"
        "						nAllNull = false;\n"
        "						break;\n"
        "					}\n"
        "				}\n"
        "				if(!nAllNull)	\n"
        "				{\n"
        "\n"
        "					nIsOk = ValueValidate(ele.value, j, MINIP, MAXIP );\n"
        "					if(nIsOk==true&&ele_num>4&&j==1)\n"
        "					{\n"
        "						if((document.forms[0].elements[i*ele_num+j].value==0&&\n"
        "							document.forms[0].elements[i*ele_num+j+1].value==0)||\n"
        "							(document.forms[0].elements[i*ele_num+j].value==255&&\n"
        "							document.forms[0].elements[i*ele_num+j+1].value==255))\n"
        "						{\n"
        "							alert(\"IP地址错误！请重新输入！\");\n"
        "							nIsOk = false;\n"
        "						}\n"
        "					}\n"
        "				}\n"
        "\n"
        "			}\n"
        "			if(!nIsOk)\n"
        "			{\n"
        "				ele.focus(); ele.select();\n"
        "				return false;	\n"
        "			}\n"
        "		}\n"
        "	}\n"
        "	return true;\n"
        "}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>虚拟服务器</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>虚拟服务器，简单地说，您可以做这么样的指定：对路由器任何一个或一段协议端口的访问（从WAN口进来的访问），都可以重定位到局域网内某一台指定的网络服务器。 </TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 class=space width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=12><DIV align=center>ID</DIV></TD>\n"
        "                          <TD width=109><DIV align=center>服务端口</DIV></TD>\n"
        "                          <TD width=125><DIV align=center>IP地址</DIV></TD>\n"
        "                          <TD width=70><DIV align=center>协议</DIV></TD>\n"
        "                          <TD width=62><DIV align=center>启用</DIV></TD>\n"
        "                        </TR>\n"
        "					  "
        );
    goto_ERROR;

    for (i=offset; i<offset+8; i++) {
    sprintf(protocol, "protocol%d", i);
    sprintf(enable, "enable%d", i);
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                        <TR>\n"
        "                          <TD><DIV align=center>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</DIV></TD>\n"
        "                          <TD><DIV align=center>\n"
        "                              <INPUT class=text id=port"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " maxLength=11 name=port"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=12 \n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->virtual_host[i].server_port);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            </DIV></TD>\n"
        "                          <TD><DIV align=center>192.168.1.\n"
        "                              <INPUT class=text id=ipb"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " maxLength=3 name=ipb"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=3 \n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->virtual_host[i].server_ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            </DIV></TD>\n"
        "                          <TD align=middle>\n"
        "                          "
        );
    goto_ERROR;

    SELECT_BEGIN(protocol, bbr->virtual_host[i].protocol, "class=list")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("1", "ALL")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("2", "TCP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("3", "UDP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          </TD>\n"
        "                          <TD><DIV align=center>"
        );
    goto_ERROR;

    CHECK_BOX2(enable, "1", bbr->virtual_host[i].enable, "");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          </DIV></TD>\n"
        "                          <TD>&nbsp;</TD>\n"
        "                        </TR>\n"
        "					  "
        );
    goto_ERROR;

    }
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 class=space width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=90>常用服务端口：</TD>\n"
        "                          <TD noWrap width=102>\n"
        "                          "
        );
    goto_ERROR;

    sprintf(gport, "%d", bbr->virtual_host[i].general_port);
    SELECT_BEGIN("ports", gport, "class=list id=ports")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("53", 	"DNS(53)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("21",	"FTP(21)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("3", 	"GOPHER(70)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("70", 	"HTTP(80)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("119", "NNTP(119)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("110", "POP3(110)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("1723","PPTP(1723)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("25", 	"SMTP(25)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("1080","SOCK(1080)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("23", 	"TELNET(23)")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "						  </TD>\n"
        "                          <TD noWrap width=73><INPUT class=button id=fill name=fill onclick=doFill(); type=button value=填空到>\n"
        "&nbsp;ID</TD>\n"
        "                          <TD noWrap width=117>\n"
        "                          "
        );
    goto_ERROR;

    sprintf(gport, "%d", bbr->virtual_host[i].id);
    SELECT_BEGIN("ids", gid, "class=list id=ids")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    for (i=offset; i<offset+8; i++) {
    sprintf(num, "%d", i+1);
    OPTIONS_ADD(num, num);
    }
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "						  </TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button "
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", offset<=0 ? "disabled": "");
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " id=PrevPage name=PrevPage onclick=doPrev(); type=button value=上一页>\n"
        "&nbsp;\n"
        "                    <INPUT class=button "
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", offset+8>=max_count-1 ? "disabled": "");
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " id=NextPage name=NextPage onclick=doNext(); type=button value=下一页>\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=Clear name=Clear onclick=doClear(); type=button value=\"清 空\">\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=Submit name=Save type=submit value=\"保 存\">\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "    </TABLE>\n"
        "    </TD>\n"
        "    </TR>\n"
        "    </TABLE>\n"
        "    <INPUT name=curpage type=hidden value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", ncurpage);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<BR>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _nat_virtualserver_csp__ */

static int _nat_virtualserver_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

