/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_network_lan_setting_csp.h"

/** GLOBAL **/

static int _network_lan_setting_csp___mime_header(void * __ebfp);

int _network_lan_setting_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "lan_setting.csp";
    char * __page_path = "/network/";
    char * __page_fullname = "/network/lan_setting.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    BUFCPY(bbr->lan.ip, G("lanip"));
    BUFCPY(bbr->lan.ipmask, G("lanmask"));
    
    save_bbr(bbr, errmsg);
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_network_lan_setting_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>netcfg</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "var oldIp;var oldMsk;\n"
        "\n"
        "function doLoad(){oldIp = document.forms[0].lanip.value; oldMsk=document.forms[0].lanmask.value}\n"
        "function doSubmit(){\n"
        "	if(document.forms[0].lanip.value!=oldIp || document.forms[0].lanmask.value!=oldMsk)	{\n"
        "		if(!confirm(\"LAN口IP地址的更改将导致路由器的重新启动，确定？\"))\n"
        "		{return false;}\n"
        "	}\n"
        "	if(!is_ipaddr(document.forms[0].lanip.value)) {\n"
        "		var element =document.forms[0].lanip;\n"
        "		if(element){\n"
        "			element.focus();element.select();\n"
        "		}\n"
        "		\n"
        "		return false;\n"
        "	}\n"
        "	if(!is_maskaddr(document.forms[0].lanmask.value)) {\n"
        "		var element =document.forms[0].lanmask;\n"
        "		if(element){element.focus();element.select();}\n"
        "		return false;\n"
        "	}\n"
        "	if(document.forms[0].lanip.value!=oldIp) {\n"
        "		parent.topLeftFrame.address = document.forms[0].lanip.value;\n"
        "		parent.topLeftFrame.LoadNewIp();\n"
        "	}\n"
        "	return true;\n"
        "}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY onload=doLoad();>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "    width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>LAN口设置</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页设置路由器LAN口的基本网络参数。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 class=space width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=70>MAC地址：</TD>\n"
        "                          <TD width=230>00-0A-EB-B2-6B-D8</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>IP地址：</TD>\n"
        "                          <TD><INPUT class=text id=lanip maxLength=15 name=lanip size=15 \n"
        "                  value="
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->lan.ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD vAlign=bottom>子网掩码：</TD>\n"
        "                          <TD>\n"
        "                          "
        );
    goto_ERROR;

    SELECT_BEGIN("lanmask", bbr->lan.ipmask, "class=list id=lanmask")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("255.255.255.0", "255.255.255.0")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD("255.255.0.0", "255.255.0.0")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          </TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>注意：当LAN口IP参数（包括IP地址、子网掩码）发生变更时，为确保DHCP server能够正常工作，应保证DHCP server中设置的地址池、静态地址与新的LAN口IP是处于同一网段的，并请重启路由器。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <BR></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30><DIV align=left>&nbsp;&nbsp;\n"
        "                      <INPUT class=button id=\"保 存\" name=Save type=submit value=\"保 存\">\n"
        "&nbsp;&nbsp;&nbsp;</DIV></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _network_lan_setting_csp__ */

static int _network_lan_setting_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

