/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_network_mac_setting_csp.h"

/** GLOBAL **/

static int _network_mac_setting_csp___mime_header(void * __ebfp);

int _network_mac_setting_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "mac_setting.csp";
    char * __page_path = "/network/";
    char * __page_fullname = "/network/mac_setting.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    BUFCPY(bbr->mac.wan_mac, G("mac"));
    
    save_bbr(bbr, errmsg);
    } else if (!isblankstr(G("restore"))) {
    BUFCPY(bbr->mac.wan_mac, G("defaultMac"));
    
    save_bbr(bbr, errmsg);
    }
    

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_network_mac_setting_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>mac</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function doRestore(){document.forms[0].mac.value=document.forms[0].defaultMac.value;}\n"
        "function doClone(){document.forms[0].mac.value = document.forms[0].pcmac.value;return true;}\n"
        "function is_spmac(mac_string){\n"
        "if(mac_string == \"00-00-00-00-00-00\"){\n"
        "alert(\"无效MAC地址，请重新输入！\");\n"
        "return false;}\n"
        "var ch = \"Ff-\";\n"
        "for (var i = 0; i < mac_string.length; i++){\n"
        "c = mac_string.charAt(i);\n"
        "if(ch.indexOf(c) == -1)return true;}\n"
        "alert(\"无效MAC地址，请重新输入！\");\n"
        "return false;}\n"
        "function doSubmit(){	\n"
        "if(!is_macaddr(document.forms[0].mac.value)){	\n"
        "var element = document.forms[0].mac;\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}\n"
        "if(!is_spmac(document.forms[0].mac.value)){\n"
        "var element = document.forms[0].mac;\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}\n"
        "if(!confirm(\"此功能需重启后才能生效，确定现在重启路由器？\"))\n"
        "return false;else return true;}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"  method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>MAC地址克隆</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页设置路由器对广域网的MAC地址。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 class=space width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=136>MAC地址：</TD>\n"
        "                          <TD width=264><INPUT class=text id=mac maxLength=17 name=mac \n"
        "                  size=18 value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->mac.wan_mac);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "&nbsp;\n"
        "                            <INPUT class=button id=restore name=restore onclick=doRestore(); type=button value=恢复出厂MAC></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>当前管理PC的MAC地址：</TD>\n"
        "                          <TD><INPUT class=text disabled id=pcmac maxLength=17 \n"
        "                  name=pcmac size=18 value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->mac.pc_mac);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "&nbsp;\n"
        "                            <INPUT class=button disabled id=clone name=clone onclick=doClone(); type=button value=克隆MAC地址>\n"
        "                            <INPUT name=defaultMac type=hidden value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", FACTORY_WAN_MAC);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>注意：只有局域网中的计算机能使用“克隆MAC地址”功能。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "        width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=save name=Save type=submit value=\"保 存\">\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "        width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _network_mac_setting_csp__ */

static int _network_mac_setting_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

