/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_network_pppoe_more_csp.h"

/** GLOBAL **/

static int _network_pppoe_more_csp___mime_header(void * __ebfp);

int _network_pppoe_more_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "pppoe_more.csp";
    char * __page_path = "/network/";
    char * __page_fullname = "/network/pppoe_more.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    bbr->pppoe.mtu = atoi(G("lcpMru"));
    BUFCPY(bbr->pppoe.server_name, G("ServiceName"));
    BUFCPY(bbr->pppoe.service_name, G("AcName"));
    bbr->pppoe.use_isp_ip = !strcmp(G("fixedIpEn"), "2");
    bbr->pppoe.interval = atoi(G("EchoReq"));
    bbr->pppoe.manual_set_dns = !strcmp(G("manual"), "2");
    if (bbr->pppoe.use_isp_ip)
    BUFCPY(bbr->pppoe.isp_ip, G("fixedIp"));
    if (bbr->pppoe.manual_set_dns)
    {
    BUFCPY(bbr->dhcps.main_dsn_server, G("dnsserver"));
    BUFCPY(bbr->dhcps.backup_dsn_server, G("dnsserver2"));
    }
    
    save_bbr(bbr, errmsg);
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_network_pppoe_more_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>pppoecfg</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function doPrev(){history.go(-1);}\n"
        "function doBack(){location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/network/wan_setting.csp\";}\n"
        "function doSubmit(){\n"
        "if(document.forms[0].lcpMru.value>1492 || document.forms[0].lcpMru.value<576)\n"
        "\n"
        "{alert(\"数据包的MTU值已超出范围，请重新输入(576 - 1492)！\"); return false;}\n"
        "\n"
        "if(!is_number(document.forms[0].EchoReq.value,0,120)){\n"
        "	alert(\"时间输入错误，请重新输入（0－120）！\");\n"
        "	\n"
        "	var element =document.forms[0].EchoReq;\n"
        "	if(element){element.focus();element.select();}\n"
        "	return false;\n"
        "}	\n"
        "\n"
        "if(document.forms[0].manual.checked){\n"
        "if(!is_dnsaddr(document.forms[0].dnsserver.value)){\n"
        "var element =document.forms[0].dnsserver;\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}\n"
        "if(document.forms[0].dnsserver2.value != \"\"){\n"
        "if(!is_dnsaddr(document.forms[0].dnsserver2.value)){\n"
        "var element =document.forms[0].dnsserver2;\n"
        "if(element){element.focus();element.select();}\n"
        "return false;}}}\n"
        "return true;}\n"
        "function doSet1(){if(document.forms[0].fixedIpEn.checked){\n"
        "document.forms[0].fixedIp.disabled=false;}\n"
        "else{document.forms[0].fixedIp.disabled=true;}return true;}\n"
        "function doSet(){if(document.forms[0].manual.checked){\n"
        "document.forms[0].dnsserver.disabled = false;\n"
        "document.forms[0].dnsserver2.disabled = false;}\n"
        "else{document.forms[0].dnsserver.disabled = true;\n"
        "document.forms[0].dnsserver2.disabled = true;}return true;}\n"
        "function doLoad(){\n"
        "if(document.forms[0].manual.checked){\n"
        "document.forms[0].dnsserver.disabled = false;\n"
        "document.forms[0].dnsserver2.disabled = false;}\n"
        "else{document.forms[0].dnsserver.disabled = true;\n"
        "document.forms[0].dnsserver2.disabled = true;}\n"
        "if(document.forms[0].fixedIpEn.checked)\n"
        "{document.forms[0].fixedIp.disabled=false;}\n"
        "else {document.forms[0].fixedIp.disabled=true;}\n"
        "return true;}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY onload=doLoad();>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"  method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "      \n"
        "      <TR>\n"
        "        <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "        <TD align=left class=title vAlign=center width=495>PPPoE高级设置</TD>\n"
        "      </TR>\n"
        "      <TR>\n"
        "        <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "            <TBODY>\n"
        "            \n"
        "            <TR>\n"
        "            \n"
        "            <TD class=vline rowSpan=15><BR></TD>\n"
        "            <TD width=500><TABLE align=center border=0 class=space width=460>\n"
        "                <TBODY>\n"
        "                  <TR>\n"
        "                  <TR>\n"
        "                    <TD height=36>数据包MTU ：</TD>\n"
        "                    <TD><INPUT class=text id=lcpMru maxLength=4 name=lcpMru size=4 \n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", bbr->pppoe.mtu);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                      （缺省值为1492，如非必要，请勿更改）</TD>\n"
        "                  </TR>\n"
        "                  <TR>\n"
        "                    <TD>服务名 ：</TD>\n"
        "                    <TD><INPUT class=text maxLength=31 name=ServiceName size=15\n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->pppoe.server_name);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                      （即Service Name。如非必要，请勿填写）</TD>\n"
        "                  </TR>\n"
        "                  <TR>\n"
        "                    <TD>服务器名称：</TD>\n"
        "                    <TD><INPUT class=text maxLength=31 name=AcName size=15\n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->pppoe.service_name);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                      （即AC Name。如非必要，请勿填写）</TD>\n"
        "                  </TR>\n"
        "                  <TR>\n"
        "                    <TD colSpan=2>\n"
        "                      "
        );
    goto_ERROR;

    CHECK_BOX2("fixedIpEn", "2", bbr->pppoe.use_isp_ip, "onclick=doSet1();");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                      使用ISP指定IP地址</TD>\n"
        "                  </TR>\n"
        "                  <TR>\n"
        "                    <TD>ISP指定的IP地址：</TD>\n"
        "                    <TD><INPUT class=text maxLength=15 name=fixedIp size=15\n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->pppoe.isp_ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                    </TD>\n"
        "                  <TR>\n"
        "                    <TD height=30>在线检测时间间隔：</TD>\n"
        "                    <TD><INPUT class=text maxLength=3 name=EchoReq size=3 \n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", bbr->pppoe.interval);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                      秒 （0～120，0 表示不发送）</TD>\n"
        "                  </TR>\n"
        "                </TR>\n"
        "                \n"
        "                <TR>\n"
        "                  <TD colSpan=2>\n"
        "                    "
        );
    goto_ERROR;

    CHECK_BOX2("manual", "2", bbr->pppoe.manual_set_dns, "id=manual onclick=doSet();");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                    手动设置DNS服务器</TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD>DNS服务器：</TD>\n"
        "                  <TD><INPUT class=text id=dnsserver maxLength=15 name=dnsserver size=15 \n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->dhcps.main_dsn_server);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                  </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD height=23>备用DNS服务器：</TD>\n"
        "                  <TD><INPUT class=text id=dnsserver2 maxLength=15 name=dnsserver2 size=15 \n"
        "                      value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->dhcps.backup_dsn_server);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                    （可选）</TD>\n"
        "                </TR>\n"
        "                </TBODY>\n"
        "              </TABLE>\n"
        "              <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=460>\n"
        "                <INPUT class=button name=back onclick=doBack(); type=button value=\"返 回\">\n"
        "&nbsp;\n"
        "                <INPUT name=Advanced type=hidden value=高级设置>\n"
        "                <TBODY>\n"
        "                </TBODY>\n"
        "              </TABLE></TD>\n"
        "            <TD class=vline rowSpan=15><BR></TD>\n"
        "            </TR>\n"
        "            <TR>\n"
        "              <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "            </TR>\n"
        "            <TR>\n"
        "              <TD class=tail height=30>&nbsp;\n"
        "                <INPUT class=button id=save name=Save type=submit value=\"保 存\">\n"
        "&nbsp; </TD>\n"
        "            </TR>\n"
        "            <TR>\n"
        "              <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "            </TR>\n"
        "            </TBODY>\n"
        "          </TABLE></TD>\n"
        "      </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _network_pppoe_more_csp__ */

static int _network_pppoe_more_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

