/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_network_wan_setting_csp.h"

/** GLOBAL **/

static int _network_wan_setting_csp___mime_header(void * __ebfp);

int _network_wan_setting_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "wan_setting.csp";
    char * __page_path = "/network/";
    char * __page_fullname = "/network/wan_setting.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    BUFCPY(bbr->wan.wan_type, G("wantype"));
    BUFCPY(bbr->wan.account, G("acc"));
    BUFCPY(bbr->wan.password, G("psw"));
    BUFCPY(bbr->wan.connect_mode, G("linktype"));
    if ( !strcmp(bbr->wan.connect_mode, "1") )
    bbr->wan.auto_wait_time = atoi(G("waittime"));
    if ( !strcmp(bbr->wan.connect_mode, "4") )
    bbr->wan.manual_wait_time = atoi(G("waittime2"));
    
    save_bbr(bbr, errmsg);
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_network_wan_setting_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>pppoecfg</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" type=text/JavaScript></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\"http://"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getServerAddr());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function doPrev(){history.go(-1);}\n"
        "function doSubmit(){\n"
        "	if(document.forms[0].linktype[0].checked){\n"
        "		if(!is_number(document.forms[0].waittime.value,0,99)){\n"
        "			alert(\"时间输入错误，请重新输入（0－99）！\");\n"
        "			\n"
        "			var element =document.forms[0].waittime;\n"
        "			if(element){element.focus();element.select();}\n"
        "			return false;\n"
        "		}	\n"
        "	}\n"
        "	if(document.forms[0].linktype[2].checked){\n"
        "		if(!is_number(document.forms[0].waittime2.value,0,99)){\n"
        "			alert(\"时间输入错误，请重新输入（0－99）！\");\n"
        "			var element =document.forms[0].waittime2;\n"
        "			if(element){element.focus();element.select();}\n"
        "				return false;\n"
        "		}\n"
        "	}\n"
        "	return true;\n"
        "}\n"
        "\n"
        "function doAdvance(){location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/network/pppoe_more.csp\"}\n"
        "function doSelect(){\n"
        "	if(document.forms[0].linktype[0].checked)\n"
        "		document.forms[0].waittime.disabled = false;\n"
        "	else\n"
        "		{document.forms[0].waittime.disabled = true;}\n"
        "\n"
        "	if(document.forms[0].linktype[2].checked)\n"
        "		document.forms[0].waittime2.disabled = false;\n"
        "	else\n"
        "		{document.forms[0].waittime2.disabled = true;}\n"
        "		\n"
        "	return true;\n"
        "}\n"
        "\n"
        "function doLoad(){\n"
        "	if(document.forms[0].linktype[0].checked)\n"
        "		document.forms[0].waittime.disabled = false;\n"
        "	else{document.forms[0].waittime.disabled = true;}\n"
        "	\n"
        "	if(document.forms[0].linktype[2].checked)\n"
        "		document.forms[0].waittime2.disabled = false;\n"
        "	else{document.forms[0].waittime2.disabled = true;}\n"
        "	\n"
        "	return true;\n"
        "}\n"
        "\n"
        "function doChange(){\n"
        "	return false;\n"
        );
    goto_ERROR;

    #if 0
    __ret=(int)ebBufStringAdd(__ebfp, 
        "	var n = document.forms[0].wantype.selectedIndex;\n"
        "	if(document.forms[0].wantype.selectedIndex == 0){\n"
        "		location.href = \""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";\n"
        "	}\n"
        "	if(document.forms[0].wantype.selectedIndex == 1){\n"
        "		location.href = \""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";\n"
        "	}\n"
        "	if(document.forms[0].wantype.selectedIndex == 2){\n"
        "		location.href = \""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";\n"
        "	}\n"
        );
    goto_ERROR;

    #endif
    __ret=(int)ebBufStringAdd(__ebfp, 
        "}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY onload=doLoad();>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>WAN口设置</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=460>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页设置路由器WAN口的基本网络参数。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=460>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=111>WAN口连接类型：</TD>\n"
        "                          <TD width=285>\n"
        "                          "
        );
    goto_ERROR;

    SELECT_BEGIN("wantype", bbr->wan.wan_type, "class=list onchange=doChange()")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD(WAN_TYPE_DYNAMIC_IP, "动态IP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD(WAN_TYPE_STATIC_IP, "静态IP")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                              "
        );
    goto_ERROR;

    OPTIONS_ADD(WAN_TYPE_PPPOE, "PPPoE")
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                          "
        );
    goto_ERROR;

    SELECT_END()
    __ret=(int)ebBufStringAdd(__ebfp, 
        "						  </TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 width=460>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                        <TR>\n"
        "                          <TD width=107>上网账号：</TD>\n"
        "                          <TD width=289><INPUT class=text id=acc maxLength=118 name=acc \n"
        "                  size=25 value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->wan.account);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>上网口令：</TD>\n"
        "                          <TD><INPUT class=text id=psw maxLength=118 name=psw size=25 \n"
        "                  type=password value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->wan.password);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=460>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD colSpan=2>根据您的需要，请选择对应连接模式：</TD>\n"
        "                        </TR>	\n"
        "                        <TR>\n"
        "                          <TD colSpan=2>\n"
        "                          	"
        );
    goto_ERROR;

    RADIO_BOX("linktype", "1", bbr->wan.connect_mode, "onclick=doSelect();");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                            按需连接，在有访问数据时自动进行连接。</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD width=27>&nbsp;</TD>\n"
        "                          <TD width=373>自动断线等待时间：\n"
        "                            <INPUT class=text id=waittime maxLength=2 name=waittime size=2 \n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", bbr->wan.auto_wait_time);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            分钟 （0表示不自动断线）</TD>\n"
        "                        </TR>\n"
        "                        <TR>"
        );
    goto_ERROR;

    RADIO_BOX("linktype", "2", bbr->wan.connect_mode, "onclick=doSelect();");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                            自动连接，在开机和断线后自动进行连接。</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD colSpan=2>\n"
        "                          	"
        );
    goto_ERROR;

    RADIO_BOX("linktype", "4", bbr->wan.connect_mode, "onclick=doSelect();");
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                            手动连接，由用户手动进行连接。</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>&nbsp;</TD>\n"
        "                          <TD>自动断线等待时间：\n"
        "                            <INPUT class=text id=waittime2 maxLength=2 name=waittime2 size=2 \n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", bbr->wan.manual_wait_time);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            分钟 （0表示不自动断线）</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD><INPUT class=button disabled id=connect2 name=Connect type=submit value=\"连 接\">\n"
        "&nbsp;\n"
        "                            <INPUT class=button id=disconnect2 name=Disconnect type=submit value=\"断 线\"></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=460>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD><INPUT class=button name=Advanced onclick=doAdvance(); type=button value=高级设置></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=save name=Save type=submit value=\"保 存\">\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "          width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _network_wan_setting_csp__ */

static int _network_wan_setting_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

