/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_route_static_csp.h"

/** GLOBAL **/

static int _route_static_csp___mime_header(void * __ebfp);

int _route_static_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "static.csp";
    char * __page_path = "/route/";
    char * __page_fullname = "/route/static.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    int 				i;
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Save"))) {
    char		dest_ip[16];
    char		mask[16];
    char		gateway[16];
    char		enable[16];
    for (i=0; i<MAX_STATIC_ROUTER_NUM; i++) {
    sprintf(dest_ip, "ip%d", i);
    sprintf(mask, "mask%d", i);
    sprintf(gateway, "gateway%d", i);
    sprintf(enable, "enable%d", i);
    
    BUFCPY(bbr->static_route[i].dest_ip, G(dest_ip));
    BUFCPY(bbr->static_route[i].mask, G(mask));
    BUFCPY(bbr->static_route[i].gateway, G(gateway));
    bbr->static_route[i].enable = atoi(G(enable));
    }
    
    save_bbr(bbr, errmsg);
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_route_static_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>Static Routing</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function doClear(){\n"
        "	for(var i = 0; i < 8*4; i += 4){\n"
        "		document.forms[0].elements[i].value = \"\";\n"
        "		document.forms[0].elements[i+1].value = \"\";\n"
        "		document.forms[0].elements[i+2].value = \"\";\n"
        "		document.forms[0].elements[i+3].value = \"\";\n"
        "		document.forms[0].elements[i+4].checked = 0;\n"
        "	}\n"
        "}\n"
        "function doSubmit(){\n"
        "	for(var i = 0; i < 8*4; i += 4){\n"
        "		var ip = document.forms[0].elements[i];\n"
        "		var mask = document.forms[0].elements[i+1];\n"
        "		var gateway = document.forms[0].elements[i+2];\n"
        "		var enable = document.forms[0].elements[i+3];\n"
        "		if(ip.value != \"\"){\n"
        "			if(!is_ipaddr(ip.value)){\n"
        "				var element = ip;\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}\n"
        "		}else{\n"
        "			if(mask.value != \"\" || gateway.value != \"\"){\n"
        "				alert(\"请输入目的IP地址！\");\n"
        "				var element = ip;\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}else{\n"
        "				enable.checked = false;\n"
        "			}		\n"
        "		}\n"
        "		if(mask.value != \"\"){\n"
        "			if(!is_maskaddr(mask.value)){\n"
        "				var element = mask;\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}\n"
        "		}else{\n"
        "			if(ip.value != \"\" || gateway.value != \"\"){\n"
        "				alert(\"请输入子网掩码（例如255.255.255.0）！\");\n"
        "				var element = mask;\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}else{\n"
        "				enable.checked = false;\n"
        "			}		\n"
        "		}		\n"
        "		if(gateway.value != \"\"){\n"
        "			if(!is_gatewayaddr(gateway.value)){\n"
        "				var element = gateway;\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}\n"
        "		}else{\n"
        "			if(mask.value != \"\" || ip.value != \"\"){\n"
        "				alert(\"请输入网关！\");\n"
        "				var element = gateway;\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}else{\n"
        "				enable.checked = false;\n"
        "			}		\n"
        "		}\n"
        "	}\n"
        "	for(var i = 0; i < 8*4; i += 4){\n"
        "		var ip_1 = document.forms[0].elements[i];\n"
        "		var mask_1 = document.forms[0].elements[i+1];\n"
        "		var gateway_1 = document.forms[0].elements[i+2];\n"
        "		for(var j = i + 4; j < 32; j += 4){\n"
        "			var ip_2 = document.forms[0].elements[j];\n"
        "			var mask_2 = document.forms[0].elements[j+1];\n"
        "			var gateway_2 = document.forms[0].elements[j+2];		\n"
        "			if(ip_1.value != \"\" && \n"
        "				ip_1.value == ip_2.value && \n"
        "				mask_1.value == mask_2.value &&\n"
        "				gateway_1.value == gateway_2.value){\n"
        "					alert(\" 不能有相同的路由项，请重新输入！\");\n"
        "					var element = ip_2;\n"
        "					if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "					}\n"
        "					return false;\n"
        "			}\n"
        "		}\n"
        "	}\n"
        "	return true;\n"
        "}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 \n"
        "      src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=495>静态路由表</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=502>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=400>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页设置路由器的静态路由信息。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=410>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=13><DIV align=center>ID</DIV></TD>\n"
        "                          <TD width=115><DIV align=center>目的IP地址</DIV></TD>\n"
        "                          <TD width=112><DIV align=center>子网掩码</DIV></TD>\n"
        "                          <TD width=110><DIV align=center>网关</DIV></TD>\n"
        "                          <TD width=24><DIV align=center>启用</DIV></TD>\n"
        "                        </TR>\n"
        "					  "
        );
    goto_ERROR;

    for (i=0; i<MAX_SPECIAL_APP_NUM; i++) {
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                        <TR>\n"
        "                          <TD><DIV align=center>"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i+1);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "</DIV></TD>\n"
        "                          <TD><DIV align=center>\n"
        "                              <INPUT class=text id=ip"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " maxLength=15 name=ip"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=15\n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->static_route[i].dest_ip);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            </DIV></TD>\n"
        "                          <TD><DIV align=center>\n"
        "                              <INPUT class=text id=mask"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " maxLength=15 name=mask"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=15\n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->static_route[i].mask);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            </DIV></TD>\n"
        "                          <TD><DIV align=center>\n"
        "                              <INPUT class=text id=gateway"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " maxLength=15 name=gateway"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " size=15\n"
        "                              value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->static_route[i].gateway);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\">\n"
        "                            </DIV></TD>\n"
        "                          <TD><DIV align=center>\n"
        "                              <INPUT id=enable"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " name=enable"
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%d", i);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        " type=checkbox value=2\n"
        "                              "
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->static_route[i].enable ? "checked": "");
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        ">\n"
        "                            </DIV></TD>\n"
        "                        </TR>\n"
        " 					 "
        );
    goto_ERROR;

    }
    __ret=(int)ebBufStringAdd(__ebfp, 
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 \n"
        "            src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=Clear name=Clear onclick=doClear(); type=button value=\"清 空\">\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=Submit name=Save type=submit value=\"保 存\">\n"
        "&nbsp; </TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 \n"
        "            src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "      width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _route_static_csp__ */

static int _route_static_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

