/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
                                         
/** GLOBAL **/

static int _security_domainfilter_csp___mime_header(void * __ebfp);

int _security_domainfilter_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "domainfilter.csp";
    char * __page_path = "/security/";
    char * __page_fullname = "/security/domainfilter.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_security_domainfilter_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>domainfilter</TITLE>\n"
        "<META content=\"text/html; charset=gb2312\" http-equiv=Content-Type>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "<META content=\"wed, 26 Feb 1997 08:21:57 GMT\" http-equiv=expires>\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" rel=stylesheet type=text/css>\n"
        "<STYLE type=text/css>\n"
        "A.tp3:visited {\n"
        "	COLOR: #0000ff\n"
        "}\n"
        "A.tp3:link {\n"
        "	COLOR: #0000ff\n"
        "}\n"
        "</STYLE>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function doAll(val){if(val==\"DelAll\"){if(!confirm(\"您确认要删除当前所有的条目吗？\")) return;} location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "doAll=\"+val;}\n"
        "function doAdd(nPage){location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "Add=Add&Page=\"+nPage;}\n"
        "function doPage(nPage){location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "Page=\"+nPage;}\n"
        "function ResetStatus(strInfo){window.status=strInfo;return true;}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE border=0 cellPadding=0 cellSpacing=0 width=520>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD align=left class=title vAlign=center width=513>域名过滤</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE border=0 cellPadding=0 cellSpacing=0 width=520>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=518><TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=470>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页通过域名过滤来限制局域网中计算机对指定的广域网网站的访问。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=1 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=470>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD><TABLE align=center border=0 cellPadding=0 cellSpacing=0 \n"
        "                  class=space width=450>\n"
        "                              <TBODY>\n"
        "                                <TR>\n"
        "                                  <TD colSpan=2>防火墙相关设置（如需更改，请到“安全设置”－“防火墙设置”）</TD>\n"
        "                                </TR>\n"
        "                                <TR>\n"
        "                                  <TD width=120>防火墙功能：</TD>\n"
        "                                  <TD width=328><B>关闭</B></TD>\n"
        "                                </TR>\n"
        "                                <TR>\n"
        "                                  <TD width=120>域名过滤功能：</TD>\n"
        "                                  <TD \n"
        "            width=328><B>关闭</B></TD>\n"
        "                                </TR>\n"
        "                              </TBODY>\n"
        "                            </TABLE></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=1 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=470>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD align=middle>ID</TD>\n"
        "                          <TD align=middle width=230>域 名</TD>\n"
        "                          <TD align=middle noWrap>状 态</TD>\n"
        "                          <TD align=middle>修 改</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle>1</TD>\n"
        "                          <TD align=left>&nbsp;www.zhangzhuang.com</TD>\n"
        "                          <TD align=middle>生效</TD>\n"
        "                          <TD align=middle noWrap><A class=tp3 \n"
        "                  href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "Modify=0\" \n"
        "                  onmouseover=\"return ResetStatus(\'修改\');\">修改</A>&nbsp;<A \n"
        "                  class=tp3 \n"
        "                  href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "Del=0\" \n"
        "                  onmouseover=\"return ResetStatus(\'删除\');\">删除</A></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle>2</TD>\n"
        "                          <TD align=left>&nbsp;www.xiaohezi.com</TD>\n"
        "                          <TD align=middle>生效</TD>\n"
        "                          <TD align=middle noWrap><A class=tp3 \n"
        "                  href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "Modify=1\" \n"
        "                  onmouseover=\"return ResetStatus(\'修改\');\">修改</A>&nbsp;<A \n"
        "                  class=tp3 \n"
        "                  href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "Del=1\" \n"
        "                  onmouseover=\"return ResetStatus(\'删除\');\">删除</A></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE align=center border=0 cellPadding=0 cellSpacing=0 class=space \n"
        "            width=470>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD colSpan=3 width=468><INPUT class=button name=Add onclick=doAdd(1); type=button value=添加新条目>\n"
        "&nbsp;\n"
        "                            <INPUT class=button name=EnAll onclick=\"doAll(\'EnAll\');\" type=button value=使所有条目生效>\n"
        "&nbsp;\n"
        "                            <INPUT class=button name=DisAll onclick=\"doAll(\'DisAll\');\" type=button value=使所有条目失效>\n"
        "&nbsp;\n"
        "                            <INPUT class=button name=DelAll onclick=\"doAll(\'DelAll\');\" type=button value=删除所有条目></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button disabled name=previous onclick=doPage(1); type=button value=上一页>\n"
        "&nbsp;\n"
        "                    <INPUT class=button disabled name=next onclick=doPage(2); type=button value=下一页>\n"
        "                    <INPUT name=Page type=hidden value=1>\n"
        "&nbsp;</TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META content=no-cache http-equiv=pragma>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _security_domainfilter_csp__ */

static int _security_domainfilter_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

