/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
                              
/** GLOBAL **/

static int _system_log_csp___mime_header(void * __ebfp);

int _system_log_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "log.csp";
    char * __page_path = "/system/";
    char * __page_fullname = "/system/log.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_system_log_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>System Log</TITLE>\n"
        "<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "<META http-equiv=expires content=\"wed, 26 Feb 1997 08:21:57 GMT\">\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" type=text/css rel=stylesheet>\n"
        "<SCRIPT language=Javascript><!--\n"
        "function doSubmit(){\n"
        "if(confirm(\"确认清除所有日志内容吗？\")){\n"
        "return true;}\n"
        "else {return false;}}\n"
        "function doClick(){\n"
        "location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post\" onsubmit=\"return doSubmit();\">\n"
        "    <TABLE cellSpacing=0 cellPadding=0 width=562 border=0>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD class=title vAlign=center align=left width=555>系统日志</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE cellSpacing=0 cellPadding=0 width=562 border=0>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=560><TABLE class=space cellSpacing=0 cellPadding=0 width=520 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD noWrap align=left width=60>索引</TD>\n"
        "                          <TD align=middle>日 志 内 容</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space cellSpacing=0 cellPadding=0 width=520 \n"
        "            align=center border=1>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>1</TD>\n"
        "                          <TD><P align=left>&nbsp;0051:发送PADI,请求建立连接.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>2</TD>\n"
        "                          <TD><P align=left>&nbsp;0052:PPPOE请求连接超时.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>3</TD>\n"
        "                          <TD><P align=left>&nbsp;0062:PPPoE 开启自动连接.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>4</TD>\n"
        "                          <TD><P align=left>&nbsp;0062:发送PADI,请求建立连接.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>5</TD>\n"
        "                          <TD><P align=left>&nbsp;0062:接收PADT,服务端请求断开本次连接.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>6</TD>\n"
        "                          <TD><P align=left>&nbsp;0072:PPPoE 开启自动连接.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>7</TD>\n"
        "                          <TD><P align=left>&nbsp;0072:发送PADI,请求建立连接.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>8</TD>\n"
        "                          <TD><P \n"
        "                  align=left>&nbsp;0072:接收PADO,AC-Name=YongAnERX1400,AC-MAC=00901A40BD81.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>9</TD>\n"
        "                          <TD><P align=left>&nbsp;0072:发送PADR.</P></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=middle width=20>10</TD>\n"
        "                          <TD><P \n"
        "                  align=left>&nbsp;0072:接收PADS,Session-ID=0x1D79,AC-MAC=00901A40BD81.</P></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space cellSpacing=0 cellPadding=0 width=520 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD align=left>&nbsp;Time = 2003-05-01 8:28:22 1702s</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=left>&nbsp;Mode = PPPoE : L = 192.168.1.1 : W = 221.229.229.163</TD>\n"
        "                        <TR>\n"
        "                          <TD align=left>&nbsp;H-Ver = bbr v1.0 100122BA : S-Ver = 3.1.0 Build 050226 Rel.36369na</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD align=left>&nbsp;Free=1008, Busy=16, Bind=14, Inv=0/6, Bc=0/0, Dns=107, cl=48, fc=0/0, sq=2/31</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <!--内容结束--></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30><DIV align=left>&nbsp;&nbsp;\n"
        "                      <INPUT class=button onclick=doClick(); type=button value=\"刷 新\" name=Refresh>\n"
        "&nbsp;&nbsp;&nbsp;\n"
        "                      <INPUT class=button type=submit disabled value=清除所有日志 name=ClearLog>\n"
        "                    </DIV></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _system_log_csp__ */

static int _system_log_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

