/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_system_reboot_csp.h"

/** GLOBAL **/
#ifdef VXWORKS
static int vx_reboot(int code)
{
	taskDelay(30);
	reboot(0);
}
#endif /* VXWORKS */

static int _system_reboot_csp___mime_header(void * __ebfp);

int _system_reboot_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "reboot.csp";
    char * __page_path = "/system/";
    char * __page_fullname = "/system/reboot.csp";
/** DECLARE **/

/** ON_BEGIN **/
    
    /* load first */
    if (!isblankstr(G("Reboot"))) {
    #ifdef VXWORKS
    {extern int vx_reboot(int);
    taskSpawn("vx_reboot", 1, 0, 10000, (FUNCPTR)vx_reboot,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    }
    #endif
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_system_reboot_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\n"
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>backup</TITLE>\n"
        "<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "<META http-equiv=expires content=\"wed, 26 Feb 1997 08:21:57 GMT\">\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" type=text/css rel=stylesheet>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function doSubmit(){\n"
        "if(confirm(\"确认重新启动路由器？\")){\n"
        "/* location.href = \"/userRpm/SysRebootRpm.htm\"; */\n"
        "return true;}\n"
        "else {return false;}}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" \n"
        "      width=7></TD>\n"
        "          <TD class=title vAlign=center align=left width=495>重启路由器</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE class=space cellSpacing=0 cellPadding=0 width=410 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>单击此按钮将使路由器重新启动。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space cellSpacing=0 cellPadding=0 width=410 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=326><INPUT class=button id=reboot type=submit value=重启路由器 name=Reboot>\n"
        "                          </TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;</TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "            width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _system_reboot_csp__ */

static int _system_reboot_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

