/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_system_account_csp.h"

/** GLOBAL **/

static int _system_account_csp___mime_header(void * __ebfp);

int _system_account_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "account.csp";
    char * __page_path = "/system/";
    char * __page_fullname = "/system/account.csp";
/** DECLARE **/

/** ON_BEGIN **/
    BROADBAND_ROUTER 	bbr[1];
    char				errmsg[256] = "";
    int 				modified_ok = 0;
    
    /* load first */
    load_bbr(bbr, errmsg);
    
    /* save user submit */
    if (!isblankstr(G("Submit"))) {
    int 			i;
    
    if (strcmp(bbr->account.user, G("oldname")) ||
    strcmp(bbr->account.passwd, G("oldpassword")) )
    {
    modified_ok = -1;
    }
    
    /* not same with current value */
    else if (strcmp(bbr->account.user, G("newname")) ||
    strcmp(bbr->account.passwd, G("newpassword")) )
    {
    /* create session id */
    srand(time(NULL));
    for (i=0; i<8; i++) {
    bbr->account.session_id[i] = (rand() % 10) + '0';
    }
    
    /* store to configure file */
    BUFCPY(bbr->account.user, G("newname"));
    BUFCPY(bbr->account.passwd, G("newpassword"));
    save_bbr(bbr, errmsg);
    
    modified_ok = 1;
    }
    }

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_system_account_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>password</TITLE>\n"
        "<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "<META http-equiv=expires content=\"wed, 26 Feb 1997 08:21:57 GMT\">\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" type=text/css rel=stylesheet>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "function charCompareA(szname,en_limit,cn_limit){\n"
        "var c;var ch = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_\";\n"
        "if(szname.length > en_limit) return false;\n"
        "for (var i = 0; i < szname.length; i++){\n"
        "c = szname.charAt(i);\n"
        "if (ch.indexOf(c) == -1){if(szname.length > cn_limit)\n"
        "return false;}}return true;}\n"
        "function doClear(){\n"
        "for(var i = 0; i < 5; i ++){\n"
        "document.forms[0].elements[i].value = \"\";}}\n"
        "function doSubmit(){\n"
        "	for(var i = 0; i < 5; i ++){\n"
        "		if(document.forms[0].elements[i].value == \"\") {\n"
        "			alert(\"输入不能为空！\");\n"
        "			var element = document.forms[0].elements[i];\n"
        "			if(element){\n"
        "				element.focus();element.select();\n"
        "			}\n"
        "			return false;\n"
        "		} else {\n"
        "		if (0) {\n"
        "			}\n"
        "			if(!charCompare(document.forms[0].elements[i].value,14,0)){\n"
        "				alert(\"输入中含有非法字符，请您重新输入！\");\n"
        "				var element = document.forms[0].elements[i];\n"
        "				if(element){\n"
        "					element.focus();\n"
        "					element.select();\n"
        "				}\n"
        "				return false;\n"
        "			}\n"
        "			\n"
        "			if(2==i||3==i)if(!charCompareA(document.forms[0].elements[i].value,14,0)){\n"
        "			alert(\"输入中含有非法字符，请您重新输入！\\n（请不要输入字母、数字、中划线、下划线以外的字符。）\");\n"
        "			var element = document.forms[0].elements[i];\n"
        "			if(element){\n"
        "			element.focus();element.select();}\n"
        "			return false;}\n"
        "		}\n"
        "	}\n"
        "		if(document.forms[0].elements[3].value != document.forms[0].elements[4].value){\n"
        "		alert(\"新口令和确认新口令必须一致！\");\n"
        "		var element = document.forms[0].elements[4];\n"
        "		if(element){element.focus();element.select();}\n"
        "	return false;}return true;}\n"
        "\n"
        "function err_report() {\n"
        "	"
        );
    goto_ERROR;

    if (0 > modified_ok) {
    __ret=(int)ebBufStringAdd(__ebfp, 
        "	alert(\"原口令不正确!\");\n"
        "	document.forms[0].elements[1].focus();\n"
        "	document.forms[0].elements[1].select();\n"
        "	"
        );
    goto_ERROR;

    } else if (0 < modified_ok) {
    __ret=(int)ebBufStringAdd(__ebfp, 
        "	alert(\"用户名和口令修改完毕, 请重新登录!\");\n"
        "	location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", cgiPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/login.csp\";\n"
        "	"
        );
    goto_ERROR;

    }
    __ret=(int)ebBufStringAdd(__ebfp, 
        "}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY onload=\"err_report()\">\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 \n"
        "      src=\"ChangeLoginPwdRpm.files/arc.gif\" width=7></TD>\n"
        "          <TD class=title vAlign=center align=left width=495>修改登录口令</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE class=space cellSpacing=0 cellPadding=0 width=400 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>本页修改系统管理员的用户名及口令。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space height=100 cellSpacing=0 cellPadding=0 width=400 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>原用户名：</TD>\n"
        "                          <TD><INPUT class=text id=oldname maxLength=14 size=15 \n"
        "                  value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", bbr->account.user);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" name=oldname></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD width=98>原口令：</TD>\n"
        "                          <TD width=302><INPUT class=text id=oldpassword type=password \n"
        "                  maxLength=14 size=15 name=oldpassword\n"
        "                  value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", G("oldpassword"));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>新用户名：</TD>\n"
        "                          <TD><INPUT class=text id=newname maxLength=14 size=15 name=newname\n"
        "                  value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", G("newname"));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>新口令：</TD>\n"
        "                          <TD><INPUT class=text id=newpassword type=password \n"
        "                  maxLength=14 size=15 name=newpassword\n"
        "                  value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", G("newpassword"));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>确认新口令：</TD>\n"
        "                          <TD><INPUT class=text id=newpassword2 type=password \n"
        "                  maxLength=14 size=15 name=newpassword2\n"
        "                  value=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", G("newpassword2"));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\"></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 \n"
        "            src=\"ChangeLoginPwdRpm.files/empty.gif\" width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=Submit type=submit value=\"保 存\" name=Submit>\n"
        "&nbsp;\n"
        "                    <INPUT class=button id=Help onclick=doClear(); type=button value=\"清 空\" name=Help></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 \n"
        "            src=\"ChangeLoginPwdRpm.files/empty.gif\" \n"
        "    width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _system_account_csp__ */

static int _system_account_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

