/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */
/* NOTE: YOU SHOULDN'T ADD THIS FILE TO YOUR PROJECT DIRECTLY,
 * When you add `../xx_maplist.c' to your project,
 * this file will be added into your project. 
 */ 

#include <string.h>
#include <eblib.h>
#include "_system_upgrade_csp.h"

/** GLOBAL **/

static int _system_upgrade_csp___mime_header(void * __ebfp);

int _system_upgrade_csp__ (int __calldepth, void * __handle, void * __ebfp)
{
    int __ret = OK;
    char * __page_name = "upgrade.csp";
    char * __page_path = "/system/";
    char * __page_fullname = "/system/upgrade.csp";
/** DECLARE **/

/** ON_BEGIN **/

    if (__calldepth==MAX_CALL_DEPTH)
        __ret=_system_upgrade_csp___mime_header(__ebfp);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<HTML>\n"
        "<HEAD>\n"
        "<TITLE>update</TITLE>\n"
        "<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "<META http-equiv=expires content=\"wed, 26 Feb 1997 08:21:57 GMT\">\n"
        "<LINK \n"
        "href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/bbr.css\" type=text/css rel=stylesheet>\n"
        "<SCRIPT language=JavaScript src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/commonfuncs1.js\" \n"
        "type=text/JavaScript><!--\n"
        "//--></SCRIPT>\n"
        "<SCRIPT language=JavaScript><!-- \n"
        "if(window.parent == window){window.location.href=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", getScriptName());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\";}\n"
        "function Click(){ window.event.returnValue=false;}\n"
        "document.oncontextmenu=Click;\n"
        "var bClick=false;\n"
        "function doSubmit(){\n"
        "if(bClick==true)\n"
        "return false;\n"
        "if(document.forms[0].filename.value != \"\"){\n"
        "if(!charCompare(document.forms[0].filename.value,20,0)){	\n"
        "alert(\"文件名中含有非法字符，请重新输入！\");\n"
        "var element =document.forms[0].filename;\n"
        "if(element){\n"
        "element.focus();element.select();}return false;}}\n"
        "else{alert(\"请输入文件名！\");\n"
        "var element =document.forms[0].filename;\n"
        "if(element){\n"
        "element.focus();\n"
        "element.select();}\n"
        "return false;}\n"
        "if(!is_ipaddr(document.forms[0].ip.value)){ \n"
        "var element =document.forms[0].ip;\n"
        "if(element){\n"
        "element.focus();\n"
        "element.select();}\n"
        "return false;}\n"
        "if(confirm(\"确认要进行软件升级吗\?\")){\n"
        "bClick=true;return true;}else{return false;}}\n"
        "//--></SCRIPT>\n"
        "</HEAD>\n"
        "<BODY>\n"
        "<CENTER>\n"
        "  <FORM action=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", thisCgiPrefix());
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "\" method=post onsubmit=\"return doSubmit();\">\n"
        "    <TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "      <TBODY>\n"
        "        <TR>\n"
        "          <TD class=title width=7><IMG height=24 \n"
        "      src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/arc.gif\" width=7></TD>\n"
        "          <TD class=title vAlign=center align=left width=495>软件升级</TD>\n"
        "        </TR>\n"
        "        <TR>\n"
        "          <TD colSpan=2><TABLE cellSpacing=0 cellPadding=0 width=502 border=0>\n"
        "              <TBODY>\n"
        "                <TR>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                  <TD width=500><TABLE class=space cellSpacing=0 cellPadding=0 width=400 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD>通过升级本路由器最新版本的软件，将会使您的路由器工作得更加的稳定，甚至获得更新的功能。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space cellSpacing=0 cellPadding=0 width=400 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD width=105>文 件 名：</TD>\n"
        "                          <TD width=295><INPUT class=text id=filename maxLength=20 disabled\n"
        "                  value=bbr-v1.02.bin name=filename></TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>TFTP 服务器 IP：</TD>\n"
        "                          <TD><INPUT class=text id=ip maxLength=15 disabled value=\"\" name=ip></TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE>\n"
        "                    <TABLE class=space cellSpacing=0 cellPadding=0 width=400 \n"
        "            align=center border=0>\n"
        "                      <TBODY>\n"
        "                        <TR>\n"
        "                          <TD height=50>当前软件版本："
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", BBR_VERSION);
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "<BR>\n"
        "                            当前硬件版本：V0.1.0</TD>\n"
        "                        </TR>\n"
        "                        <TR>\n"
        "                          <TD>注意：<FONT \n"
        "                  color=red>升级时请选择与当前硬件版本一致的软件。</FONT>升级过程不能关闭路由器电源，否则将导致路由器损坏而无法使用。升级过程约20秒，当升级结束后，路由器将会自动重新启动。</TD>\n"
        "                        </TR>\n"
        "                      </TBODY>\n"
        "                    </TABLE></TD>\n"
        "                  <TD class=vline rowSpan=15><BR></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 \n"
        "            src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" width=1></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=tail height=30>&nbsp;\n"
        "                    <INPUT class=button id=Submit type=submit disabled value=\"升 级\" name=Submit></TD>\n"
        "                </TR>\n"
        "                <TR>\n"
        "                  <TD class=hline><IMG height=1 \n"
        "            src=\""
        );
    goto_ERROR;

    __ret = (int)ebprintf(__ebfp, "%s", romPrefix(NULL));
    goto_ERROR;

    __ret=(int)ebBufStringAdd(__ebfp, 
        "/rom/empty.gif\" \n"
        "    width=1></TD>\n"
        "                </TR>\n"
        "              </TBODY>\n"
        "            </TABLE></TD>\n"
        "        </TR>\n"
        "      </TBODY>\n"
        "    </TABLE>\n"
        "  </FORM>\n"
        "</CENTER>\n"
        "<META http-equiv=pragma content=no-cache>\n"
        "</BODY>\n"
        "</HTML>\n"
        );

    goto_ERROR;

/** ON_END **/
ON_END:

    if ((__calldepth==MAX_CALL_DEPTH) && ERROR == ebBufFlush(__ebfp))
        return ERROR;

    return __ret;

    EB_REMOVE_NOUSED_WARNING();
} /* _system_upgrade_csp__ */

static int _system_upgrade_csp___mime_header(void * __ebfp) 
{
    return ebprintf(__ebfp, "Content-Type: text/html\n\n");
}

