/* NOTE: DO NOT EDIT THIS FILE,
 * this file is created by tool (CSP/eybuild 1.0.3) automaticly,
 * build at: Mon Oct 09 23:31:48 2006
 */

#include <ebfrm.h>

#ifdef __cplusplus
extern "C" {
#endif

extern EB_ROM_MAPFILE rom_maplist[13];

#ifdef __cplusplus
}
#endif

